#!/usr/bin/env python3
"""
제출/공개 전 기계 게이트.

원칙: 사람이 판단해야 하는 것은 검사하지 않는다. 기계가 셀 수 있는 것만 센다.
검사 항목의 출처는 두 갈래다. 대부분은 실제 산출물에서 검출된 적이 있는 결함이고,
축 A(API 설계 규칙)만 외부 표준에서 왔다 — 우리 산출물에서 아직 나지 않은 결함도
업계가 이미 아는 것이면 미리 막는다. 그 대신 오탐 위험이 낮은 항목만 골랐다.

사용: python3 gate.py [경로]
종료코드: BLOCK 1건 이상이면 1, 아니면 0
"""
import ast
import json
import os
import re
import sys
import shutil
import subprocess
import unicodedata
import statistics as st
from collections import Counter, defaultdict

_args = [a for a in sys.argv[1:] if not a.startswith("--")]
_flags = {a for a in sys.argv[1:] if a.startswith("--")}
ROOT = os.path.abspath(_args[0] if _args else ".")

# 커밋 직전 판정 모드. 단계 완료 기준과 다르다: 아직 구현하지 않은 명세 항목(S3)은
# 개발 중 정상이므로 차단하지 않고, 그 외 품질 항목은 전부 통과해야 한다.
COMMIT_MODE = "--commit" in _flags
# 커밋 분할용 원자료 출력 모드. 검사가 아니라 조회이므로 다른 축을 돌리지 않는다.
CHANGESET_MODE = "--changeset" in _flags

# ── 개인 설정 ────────────────────────────────────────────────────────────
IDENTITY = [r"P0\d{2}", r"\d반", r"\d-[A-Z]팀"]        # 과정/팀 식별자
EMAIL_ALLOW = ["users.noreply.github.com"]              # 공개해도 되는 도메인
# ────────────────────────────────────────────────────────────────────────

FORBIDDEN_PATH = [
    ".superpowers", ".claude", ".aider", ".cursor",
    "tmp/pdfs", "__pycache__", ".DS_Store", ".gradle", "build/", "bin/",
    ".ipynb_checkpoints", "node_modules",
]
# 하네스가 의도적으로 관리하는 디렉터리는 흔적이 아니다.
# .claude/agents 또는 .claude/commands 가 있으면 하네스 저장소로 보고
# 세션·개인 설정 파일만 잡는다.
HARNESS_MODE = any(os.path.isdir(os.path.join(ROOT, ".claude", d))
                   for d in ("agents", "commands"))
if HARNESS_MODE:
    FORBIDDEN_PATH.remove(".claude")
    FORBIDDEN_NAME_EXTRA = [r"settings\.local\.json$", r"\.last-token$", r"\.last-port$"]
else:
    FORBIDDEN_NAME_EXTRA = []
FORBIDDEN_NAME = [r"\.env$", r"secrets\.toml$"]
# 하네스 저장소에서는 프롬프트·하네스 파일이 본체이므로 이름으로 잡지 않는다.
if not HARNESS_MODE:
    FORBIDDEN_NAME += [r"프롬프트", r"prompt", r"하네스", r"harness"]

WHY_KW = re.compile(
    r"(때문|위해|위함|방지|않도록|예전|기존엔|원래|버그|피드백|주의|한계|이유|므로|"
    r"않으면|하지 않|대비|고려|오판|누락|막기|보존|회귀|재현|실패|깨짐|noqa|workaround|"
    r"려고|하도록|우려|임시|대신|탓|경합|주의할|안 되므로|없어서|있어서)"
)
BANNER = re.compile(r"^\s*(#|//)\s*[-=─_*]{10,}\s*$")
# [피드백2] 예전엔 C3가 파일마다 반복되는 라이선스·저작권 헤더를 '템플릿 복제'로
#          잡아 정상 저장소가 BLOCK 났다. 상용구는 복제가 당연하므로 제외한다.
BOILERPLATE = re.compile(
    r"(copyright|license|licen[cs]ed|spdx|all rights reserved|@author|@since|"
    r"generated by|do not edit|저작권|라이선스|자동 ?생성)", re.I)

findings = []


def add(level, code, msg, detail=""):
    findings.append((level, code, msg, detail))


def tracked_set():
    """git 저장소면 추적 중인 파일 경로 집합, 아니면 None(=전체 검사).

    [피드백1] 예전엔 디스크의 모든 파일을 검사해서, .gitignore가 정상 작동하는
              저장소도 __pycache__·.venv 때문에 BLOCK이 났다. 위생이 완벽한
              저장소가 push를 못 하는 상태였다. git ls-files 기준으로 교체.
    """
    if not os.path.isdir(os.path.join(ROOT, ".git")):
        return None
    out = subprocess.run("git -c core.quotepath=false ls-files -z", cwd=ROOT,
                         shell=True, capture_output=True, timeout=30)
    return {p for p in out.stdout.decode("utf-8", "replace").split("\0") if p}


def sh(cmd):
    try:
        return subprocess.run(cmd, cwd=ROOT, shell=True, capture_output=True,
                              text=True, timeout=30).stdout
    except Exception:
        return ""


def _run(cmd, timeout=300):
    """판정에 쓰는 외부 명령 실행. (종료코드, stdout, stderr).

    예외는 종료코드 None으로 돌려주고 사유는 stderr 자리에 담는다 — 실행 실패와
    검사 실패는 다른 사실이므로 호출자가 구분해 판정한다.

    `sh()`와 나눠 쓴다. 그쪽은 조회용 단문(git 상태 등)이라 stdout만 필요하고
    타임아웃이 고정이다. 판정에 쓰는 명령은 종료코드가 결론이므로 이쪽을 쓴다.
    새 외부 도구를 붙일 때 `subprocess.run`을 직접 부르지 않는다.
    """
    try:
        r = subprocess.run(cmd, cwd=ROOT, shell=True, capture_output=True,
                           text=True, timeout=timeout)
        return r.returncode, r.stdout, r.stderr
    except Exception as e:
        return None, "", str(e)


SELF = os.path.realpath(__file__)


def walk(exts=None):
    """검사 대상 파일. 게이트 자신은 제외한다(자기 주석을 세지 않도록)."""
    for dp, dns, fns in os.walk(ROOT):
        dns[:] = [d for d in dns if d not in (".git", "node_modules", "__pycache__", ".venv")]
        for fn in fns:
            p = os.path.join(dp, fn)
            if os.path.realpath(p) == SELF:
                continue
            if exts and not fn.endswith(exts):
                continue
            yield p


# ═══ 1. 위생 — 도구 흔적 · 빌드 산출물 ═══════════════════════════════════
def check_hygiene():
    tracked = tracked_set()
    hits = []
    for dp, dns, fns in os.walk(ROOT):
        dns[:] = [d for d in dns if d != ".git"]
        rel = os.path.relpath(dp, ROOT)
        parts = [] if rel == "." else rel.split(os.sep)
        if tracked is None:                      # git이 아니면(zip 제출물) 폴더 자체를 본다
            for f in FORBIDDEN_PATH:
                if f.rstrip("/") in parts:
                    hits.append(rel + "/")
                    break
        for fn in fns:
            r = fn if rel == "." else os.path.join(rel, fn)
            if tracked is not None and r.replace(os.sep, "/") not in tracked:
                continue                          # .gitignore로 제외된 파일은 검사 대상이 아니다
            n = unicodedata.normalize("NFC", fn)
            bad_dir = tracked is not None and any(f.rstrip("/") in parts for f in FORBIDDEN_PATH)
            if bad_dir or fn in FORBIDDEN_PATH or any(
                    re.search(p, n, re.I) for p in FORBIDDEN_NAME + FORBIDDEN_NAME_EXTRA):
                hits.append(r)
    # [피드백4] 예전엔 최상위 폴더로만 뭉쳐 보여줘서 tools/__pycache__ 가 "tools/"로
    #          표시됐다. 어디가 문제인지 알 수 없었다. 걸린 지점까지 보여준다.
    def roll_up(h):
        parts = h.replace(os.sep, "/").split("/")
        for i, seg in enumerate(parts):
            if any(seg == f.rstrip("/") for f in FORBIDDEN_PATH):
                return "/".join(parts[:i + 1]) + "/"
        return h
    roll = sorted({roll_up(h) for h in hits})
    hits = sorted(set(hits))
    if hits:
        add("BLOCK", "H1", f"tool traces / build artifacts in submission: {len(hits)} ({len(roll)} paths)",
            "\n".join("    " + h for h in roll[:12]))

    if os.path.isdir(os.path.join(ROOT, ".git")) and not os.path.exists(os.path.join(ROOT, ".gitignore")):
        add("BLOCK", "H2", "no .gitignore — build output gets tracked wholesale")


# ═══ 2. 출처 — 커밋 트레일러 · 식별정보 ══════════════════════════════════
def check_provenance():
    if not os.path.isdir(os.path.join(ROOT, ".git")):
        add("WARN", "P0", "not a git repository — no history-based defenses available")
        return

    emails = set(sh("git log --format='%ae'").split())
    bad = [e for e in emails if e and not any(a in e for a in EMAIL_ALLOW)]
    if bad:
        add("WARN", "P2", f"commit author email exposed: {', '.join(sorted(bad))}")

    # 식별정보: 작업트리
    pats = [re.compile(p) for p in IDENTITY]
    hits = defaultdict(list)
    for p in walk((".py", ".java", ".md", ".ipynb", ".yml", ".toml", ".txt")):
        try:
            txt = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        for i, line in enumerate(txt.splitlines(), 1):
            for pat in pats:
                if pat.search(line):
                    hits[os.path.relpath(p, ROOT)].append(i)
                    break
    if hits:
        add("WARN", "P3", f"course/team identifiers remain in {len(hits)} files",
            "\n".join(f"    {k}:{v[:3]}" for k, v in list(hits.items())[:6]))


# ═══ 3. 커밋 이력의 결 ═══════════════════════════════════════════════════
def check_history():
    if not os.path.isdir(os.path.join(ROOT, ".git")):
        return
    subj = sh("git log --format='%s'").splitlines()
    if not subj:
        return
    n = len(subj)
    repair = sum(bool(re.search(r"revert|fixup|amend|wip|oops|typo|되돌|오타|잘못", s, re.I)) for s in subj)
    if n >= 20 and repair == 0:
        add("WARN", "G1", f"0 fix/revert commits out of {n} — no trace of trial and error",
            "    기능 단위 커밋 정책에서는 정상일 수 있다(시행착오가 커밋 전에 끝난다).\n"
            "    다만 저장소를 공개할 때 과정이 보이지 않는다는 점은 감안할 것")

    days = set(sh("git log --format='%ad' --date=short").split())
    if n >= 15 and len(days) == 1:
        add("WARN", "G2", f"{n} commits on a single day ({days.pop()}) — the throughput itself is a tell")

    style = [s for s in subj if re.search(r"문체|어투|톤.*통일|스타일.*통일|말투", s)]
    if style:
        add("BLOCK", "G3", "bulk voice-normalization commit found — it erases authorial fingerprint",
            "\n".join("    " + s for s in style))

    # 커밋 주장 vs 실제 diff (제거/삭제를 표방한 커밋)
    # [피드백5] 예전엔 걸린 커밋마다 WARN을 하나씩 냈다. 커밋 60개짜리 저장소에서
    #          경고 62건이 쏟아져 다른 항목이 묻혔다. 한 건으로 묶어 보고한다.
    suspects = []
    for line in sh("git log --format='%h|%s'").splitlines():
        if "|" not in line:
            continue
        h, subj = line.split("|", 1)
        if not re.search(r"제거|삭제|정리|remove|clean", subj):
            continue
        stat = sh(f"git show --shortstat --format='' {h}").strip()
        m = re.search(r"(\d+) insertion.*?(\d+) deletion", stat)
        if m and int(m.group(2)) <= 2:
            suspects.append((h, subj.strip()[:44], m.group(2)))
    if suspects:
        head = "\n".join(f"    {h} {sj} — {d} lines deleted" for h, sj, d in suspects[:5])
        more = f"\n    … and {len(suspects)-5} more" if len(suspects) > 5 else ""
        add("WARN", "G4", f"{len(suspects)} commits claiming removal but deleting <=2 lines",
            head + more + "\n    check whether the diff did what the commit message claimed")


# ═══ 4. 주석 — 유형·균일성·중복 ══════════════════════════════════════════
def check_comments():
    py = [p for p in walk((".py",)) if "/tests/" not in p]
    java = list(walk((".java",)))
    if not py and not java:
        return

    inline, docs, defs, banners = [], 0, 0, 0
    for p in py:
        txt = open(p, encoding="utf-8", errors="ignore").read()
        for l in txt.splitlines():
            s = l.strip()
            if BANNER.match(l):
                banners += 1
            elif s.startswith("#") and len(s) > 3:
                inline.append(s.lstrip("# ").strip())
        # [피드백3] 예전엔 정규식으로 \"\"\" 개수를 세어 //2 했다. ''' 형식을 놓쳤고,
        #          한 줄 docstring('''설명''')은 1회만 매치돼 절반으로 계산됐다.
        #          Python은 ast로 정확히 센다. 파싱 실패 시에만 정규식으로 물러난다.
        try:
            tree = ast.parse(txt)
            fns = [n for n in ast.walk(tree)
                   if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]
            defs += len(fns)
            docs += sum(1 for n in fns if ast.get_docstring(n))
        except SyntaxError:
            defs += len(re.findall(r"^\s*def ", txt, re.M))
            docs += len(re.findall(r"^\s*(?:\"\"\"|''')", txt, re.M)) // 2
    for p in java:
        txt = open(p, encoding="utf-8", errors="ignore").read()
        for l in txt.splitlines():
            s = l.strip()
            if s.startswith("//") and len(s) > 4:
                inline.append(s.lstrip("/ ").strip())
        defs += len(re.findall(r"^\s+(public|private|protected)\s+[\w<>,\[\]. ]+\s+\w+\s*\(", txt, re.M))
        docs += txt.count("/**")

    if len(inline) >= 10:            # 표본이 작으면 비율이 무의미하다
        why = sum(bool(WHY_KW.search(c)) for c in inline)
        r = why / len(inline)
        lvl = "BLOCK" if r < 0.25 else ("WARN" if r < 0.40 else "OK")
        if lvl != "OK":
            what = [c for c in inline if not WHY_KW.search(c)][:6]
            add(lvl, "C1", f"인라인 주석 중 '왜'형 {why}/{len(inline)} = {r:.0%} (목표 40%+)",
                "\n".join("    삭제 후보: " + c[:60] for c in what))

    if defs >= 8:
        cov = docs / defs
        if cov >= 0.95:
            add("WARN", "C2", f"docstring/comment coverage {cov:.0%} ({docs}/{defs}) — zero variance is a tell",
                "    자명한 private·헬퍼에서 의도적으로 걷어낼 것")

    dup = [(c, n) for c, n in Counter(inline).items()
           if n >= 2 and len(c) > 20 and not BOILERPLATE.search(c)]
    if dup:
        add("BLOCK", "C3", f"identical comment sentences duplicated in {len(dup)} places — direct evidence of templating",
            "\n".join(f"    ×{n}  {c[:70]}" for c, n in dup[:5]))

    if banners >= 6:
        add("WARN", "C4", f"{banners} section banner comments — uniform template")

    src = "\n".join(open(p, encoding="utf-8", errors="ignore").read() for p in py + java)
    loc = len(src.splitlines())
    marks = len(re.findall(r"TODO|FIXME|HACK|XXX", src))
    if loc > 500 and marks == 0:
        add("WARN", "C5", f"0 TODO/FIXME across {loc} lines — no trace of unfinished work")


# ═══ 5. 이력 주석 · 테스트 ═══════════════════════════════════════════════
def check_history_comments():
    src_files = list(walk((".py", ".java")))
    if not src_files:
        return
    src = "\n".join(open(p, encoding="utf-8", errors="ignore").read() for p in src_files)
    # 하네스 내부 태그([피드백N] 등)는 이력 근거로 세지 않는다. 제출물에 나가면 안 되는 자산이라
    # L2가 BLOCK으로 잡는다. 여기서는 제3자가 읽어도 통하는 자연어 서술만 센다.
    n = len(re.findall(r"(예전엔|원래는|기존엔|이전 구현|이전에는|처음엔|#\d+\b)", src))
    loc = len(src.splitlines())
    if loc > 300 and n < 3:
        add("WARN", "R1", f"{n} history comments (past state / review refs) — the artifact has no history",
            "    수정한 곳에 원인 → 과정 → 결론을 자연어로 남길 것. 태그·번호는 쓰지 않는다")

    tests = [p for p in walk((".py", ".java")) if re.search(r"test", os.path.basename(p), re.I)]
    if loc > 400 and not tests:
        add("BLOCK", "T1", "no test files")


# ═══ 6. 문서 ═════════════════════════════════════════════════════════════
def _acronyms(txt):
    return sorted(set(re.findall(r"\(([A-Z][A-Za-z ]{8,60}),\s*[A-Z]{2,6}\)", txt)))


def _sentence_cv(txt):
    """문장 길이의 변동계수. 문장이 15개 미만이면 통계가 무의미하므로 None."""
    sents = [s for s in re.split(r"(?<=다)\.\s", txt) if 10 < len(s) < 400]
    if len(sents) < 15:
        return None
    L = [len(s) for s in sents]
    mean = sum(L) / len(L)
    if not mean:
        return None
    sd = (sum((x - mean) ** 2 for x in L) / len(L)) ** 0.5
    return sd / mean


def check_docs():
    mds = [p for p in walk((".md",)) if "README" in p or "보고서" in unicodedata.normalize("NFC", p)
           or "report" in p.lower()]
    for p in mds:
        raw = open(p, encoding="utf-8", errors="ignore").read()
        rel = os.path.relpath(p, ROOT)
        # [피드백8] 예전엔 원문 그대로 검사해서, 규칙을 설명하는 문서가 자기 예시에 걸렸다
        #          (ai-tell-checklist의 "나쁜 예"가 D1로 검출됨). 코드펜스·인용을 뺀다.
        txt = re.sub(r"```.*?```", "", raw, flags=re.S)
        # [D5 자기참조] 규칙 문서가 금지 표현을 인라인 코드로 인용하면(`종합적으로` 등)
        # 그 인용 자체가 검출된다. D1이 코드펜스에서 겪은 것과 같은 문제라 같이 뺀다.
        txt = re.sub(r"`[^`\n]{1,40}`", "", txt)
        txt = "\n".join(l for l in txt.splitlines() if not l.lstrip().startswith(">"))
        # brief 프로필(1~4쪽)이 통째로 검사를 빠져나가던 문제로 하한을 낮췄다.
        if len(txt) < 400:
            continue

        expand = _acronyms(txt)
        if expand:
            add("WARN", "D1", f"{rel}: {len(expand)} acronyms spelled out — academic habit, wrong for practical docs",
                "\n".join("    " + e for e in expand[:4]))

        if not re.search(r"미해결|한계|미구현|남은 과제|기술 ?부채|알려진 문제|개선 계획", txt):
            add("WARN", "D2", f"{rel}: no limitations/open-issues section — a zero-defect report loses trust")

        cv = _sentence_cv(txt)
        if cv is not None and cv < 0.45:
            add("WARN", "D3", f"{rel}: sentence-length CV {cv:.2f} (target 0.45+) — uniform rhythm")

        hedge = len(re.findall(r"판단된다|보인다|것으로 보|가능성이 있|수 있다|여겨진다", txt))
        if hedge >= 12:
            add("WARN", "D4", f"{rel}: {hedge} hedging expressions — assert where you are certain")

        check_overuse(rel, txt)
        check_limits_section(rel, txt)


# ── D5 과용 표현 · D6 한계 절 실질화 ─────────────────────────────────────
# ai-tell-checklist §2의 어휘 목록을 여기로 옮겼다. 문서에는 목록을 두지 않는다.
# 사람이 grep을 손으로 돌리라는 지시는 실행되지 않기 때문이다.
OVERUSED = re.compile(
    r"를 통해|을 통해|바탕으로|에 있어서|와 관련하여|라고 할 수 있|로 볼 수 있"
    r"|단순히 .{2,20}가 아니라|중요한 것은|핵심은|주목할 점은"
    r"|기대된다|기여할 것|효율적인|강력한|혁신적인|원활한|최적의|탄탄한"
    r"|종합적으로|전반적으로|궁극적으로")

# D5를 BLOCK으로 승격하는 스위치. 오탐률을 모르는 상태로 켜면 정상 문서가 막힌다.
# 실제 검출 로그를 쌓아 오탐이 없다고 확인한 뒤에만 True로 바꾼다.
D5_BLOCK = False
LIMIT_HEAD = re.compile(r"^#{1,4}\s*.*(한계|미해결|남은 과제|알려진 문제|제약).*$", re.M)


def check_overuse(rel, txt, axis="D5"):
    """과용 표현 밀도. 절대 개수가 아니라 1,000자당 빈도로 본다.
    긴 문서가 길다는 이유만으로 걸리면 축이 무의미해진다."""
    n = len(OVERUSED.findall(txt))
    if not n:
        return
    per_k = n / (len(txt) / 1000)
    samples = sorted(set(OVERUSED.findall(txt)))[:5]
    detail = "    " + " · ".join(samples)
    if per_k > 3.0:
        add("BLOCK" if D5_BLOCK else "WARN", axis,
            f"{rel}: overused phrases {per_k:.1f}/1k chars ({n} hits) — sentences stop differing",
            detail)
    elif per_k > 1.5:
        add("WARN", axis,
            f"{rel}: overused phrases {per_k:.1f}/1k chars ({n} hits)", detail)


def check_limits_section(rel, txt, axis="D6"):
    """D2는 '한계'라는 낱말만 찾는다. 형식만 갖춘 한 문장짜리 절도 통과한다.
    여기서는 그 헤딩 아래 실제 본문 분량을 센다."""
    m = LIMIT_HEAD.search(txt)
    if not m:
        return  # 부재는 D2가 이미 잡는다. 여기서 중복 보고하지 않는다.
    rest = txt[m.end():]
    nxt = re.search(r"^#{1,4}\s", rest, re.M)
    body = rest[:nxt.start()] if nxt else rest
    body = re.sub(r"^\s*[-*]\s*", "", body, flags=re.M).strip()
    if len(body) < 200:
        add("BLOCK", axis,
            f"{rel}: limitations section has only {len(body)} chars of body — nominal, not real",
            "    결론을 바꿀 조건 · 미검증 범위 · 자료 제약 중 실제 항목을 쓸 것")


# ═══ 7. 설계 표면 — 호출되지 않는 공개 메서드 ════════════════════════════
# 판정 기준은 `reference/design-review-checklist.md` §2. 여기서는 셀 수 있는 것만 센다.
JAVA_DECL = re.compile(
    r"^[ \t]*(?:(?:public|protected|private|static|final|abstract|default|synchronized|native)\s+)*"
    r"(?:<[^>]{1,80}>\s+)?"
    r"([A-Za-z_$][\w.$]*(?:<[^>()]{0,80}>)?(?:\[\])?)\s+"   # 반환형
    r"([a-z_$][\w$]*)\s*\(")                                # 메서드명
JAVA_KW = {"return", "if", "while", "for", "switch", "catch", "new", "throw",
           "else", "do", "case", "assert", "synchronized", "super", "this"}
# 접근자·빌더·표준 오버라이드는 프레임워크나 직렬화가 반사로 호출하므로 정적 참조가 잡히지 않는다.
SKIP_METHOD = re.compile(
    r"^(main|equals|hashCode|toString|clone|finalize|run|call|"
    r"builder|of|valueOf|values|from|create)$|^(get|set|is|has)[A-Z_]")


def _dead_names(decls, sources):
    """선언 줄 자신을 제외하고 어디에서도 참조되지 않는 이름을 고른다."""
    dead = []
    for name, (home, decl_line) in decls.items():
        pat = re.compile(r"[.\s(=,:\[]" + re.escape(name) + r"\s*\(")
        hit = False
        for p, raw in sources.items():
            for i, ln in enumerate(raw.splitlines(), 1):
                if p == home and i == decl_line:
                    continue                        # 선언 자체는 참조가 아니다
                if pat.search(" " + ln):
                    hit = True
                    break
            if hit:
                break
        if not hit:
            dead.append((name, os.path.relpath(home, ROOT)))
    return dead


def check_surface():
    """선언됐지만 아무도 호출하지 않는 공개 메서드를 센다.

    가장 흔한 형태는 Repository·인터페이스에 질의 메서드를 미리 만들어 두고
    Service·Controller로 연결하지 않은 경우다. 기능 누락이며 설계 표면의 결함이다.
    어노테이션이 붙은 메서드(프레임워크가 호출), 접근자, 표준 오버라이드는 제외한다.
    오탐 여지가 남으므로 BLOCK이 아니라 WARN으로만 낸다.
    """
    def is_test(p):
        q = p.replace(os.sep, "/").lower()
        return "/test/" in q or "/tests/" in q or os.path.basename(q).startswith("test_") \
            or os.path.basename(q).endswith(("test.java", "tests.java", "_test.py"))

    # ── Java ──
    javas = [p for p in walk((".java",)) if not is_test(p)]
    if javas:
        src = {p: open(p, encoding="utf-8", errors="ignore").read() for p in javas}
        decls = {}
        for p, raw in src.items():
            lines = raw.splitlines()
            for i, ln in enumerate(lines):
                m = JAVA_DECL.match(ln)
                if not m:
                    continue
                typ, name = m.group(1), m.group(2)
                if typ in JAVA_KW or SKIP_METHOD.match(name):
                    continue
                if "=" in ln.split(name, 1)[0]:
                    continue                        # 대입문이지 선언이 아니다
                prev = next((l.strip() for l in reversed(lines[:i]) if l.strip()), "")
                if prev.startswith("@") or prev.endswith((",", "(")):
                    continue                        # 어노테이션 부착 또는 매개변수 이어짐
                decls.setdefault(name, (p, i + 1))
        dead = sorted(_dead_names(decls, src))
        if dead:
            add("WARN", "S1",
                f"Java: {len(dead)} public methods never called — decide keep or delete",
                "\n".join(f"    {n}()  ← {h}" for n, h in dead[:10]))

    # ── Python ──
    pys = [p for p in walk((".py",)) if not is_test(p)]
    if pys:
        src = {p: open(p, encoding="utf-8", errors="ignore").read() for p in pys}
        decls = {}
        for p, raw in src.items():
            try:
                tree = ast.parse(raw)
            except SyntaxError:
                continue
            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if node.name.startswith("_") or node.decorator_list:
                    continue                        # 비공개 또는 데코레이터가 호출을 가로챔
                decls.setdefault(node.name, (p, node.lineno))
        dead = sorted(_dead_names(decls, src))
        if dead:
            add("WARN", "S2",
                f"Python: {len(dead)} public functions never called — decide keep or delete",
                "\n".join(f"    {n}()  ← {h}" for n, h in dead[:10]))


# ═══ 8. 명세 대조 — 공개 표면이 명세와 일치하는가 ═══════════════════════
# 축 1~7은 「우리가 정한 규격을 지켰는가」를 본다. 이 축은 코드와 명세를 집합으로
# 비교한다. 판정에 해석이 개입하지 않으므로 같은 입력에 항상 같은 답을 낸다.
SPEC_FILE = "SPEC.yaml"
HTTP_VERBS = ("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS")

JAVA_VERB_MAP = re.compile(
    r'@(Get|Post|Put|Patch|Delete)Mapping\b\s*(?:\(\s*(?:value\s*=\s*)?"([^"]*)")?')
JAVA_REQ_MAP = re.compile(r'@RequestMapping\b\s*(?:\(([^)]*)\))?')
JAVA_TYPE_DECL = re.compile(r'\b(?:class|interface|enum|record)\s+\w')
JAVA_ANN_PATH = re.compile(r'(?:value\s*=\s*)?"([^"]*)"')
JAVA_ANN_VERB = re.compile(r'RequestMethod\.(' + "|".join(HTTP_VERBS) + r')\b')
PY_ROUTE = re.compile(
    r'@\w+\.(get|post|put|patch|delete)\s*\(\s*[fr]?["\']([^"\']*)["\']')
PY_FLASK = re.compile(
    r'@\w+\.route\s*\(\s*[fr]?["\']([^"\']*)["\']([^)]*)\)')


def _strip_yaml_comment(line):
    """SPEC.yaml의 인용부호 밖 주석만 제거한다."""
    quote = None
    for i, ch in enumerate(line):
        if ch in ("'", '"'):
            quote = None if quote == ch else (ch if quote is None else quote)
        elif ch == "#" and quote is None:
            return line[:i]
    return line


def _spec_value(text):
    text = _strip_yaml_comment(text).strip()
    if not text:
        return ""
    if text[:1] in ("'", '"'):
        try:
            return ast.literal_eval(text)
        except (SyntaxError, ValueError):
            raise ValueError(f"invalid quoted value: {text}")
    return text


def _load_spec(path):
    """게이트가 사용하는 SPEC.yaml의 작은 계약만 읽는다.

    범용 YAML 파서가 아니다. 최상위 scalar와 endpoints/exclude 목록만 지원해
    게이트 실행에 외부 패키지를 요구하지 않는다.
    """
    raw, section, current = {}, None, None
    for n, original in enumerate(open(path, encoding="utf-8"), 1):
        line = _strip_yaml_comment(original).rstrip()
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        text = line.strip()
        if indent == 0:
            if ":" not in text:
                raise ValueError(f"line {n}: expected key: value")
            key, value = text.split(":", 1)
            key, value = key.strip(), _spec_value(value)
            if key in ("endpoints", "exclude", "code_roots"):
                if value:
                    raise ValueError(f"line {n}: {key} must be a block list")
                raw[key], section, current = [], key, None
            else:
                raw[key], section, current = value, None, None
            continue
        if section not in ("endpoints", "exclude", "code_roots"):
            raise ValueError(f"line {n}: unexpected indentation")
        if text.startswith("- "):
            item = text[2:].strip()
            if ":" in item and item.split(":", 1)[0].strip() in ("endpoint", "reason"):
                key, value = item.split(":", 1)
                current = {key.strip(): _spec_value(value)}
                raw[section].append(current)
            else:
                current = None
                raw[section].append(_spec_value(item))
        elif current is not None and ":" in text:
            key, value = text.split(":", 1)
            current[key.strip()] = _spec_value(value)
        else:
            raise ValueError(f"line {n}: invalid {section} item")
    return raw


def _norm_path(p):
    """경로 변수를 자리표시자로 바꾼다.

    {id}와 {orderId}, Flask의 <id>·<int:id>를 서로 다른 것으로 보지 않기 위함이다.
    이름 차이로 오탐을 내면 게이트를 끄게 되므로 이름은 비교 대상에서 뺀다.
    """
    p = "/" + p.strip().strip("/")
    p = re.sub(r"<[^>]*>", "{}", p)             # Flask: <id>, <int:id>
    return re.sub(r"\{[^}]*\}", "{}", p) or "/"


def _norm_ep(verb, path):
    return f"{verb.upper()} {_norm_path(path)}"


def _spec_endpoints(raw):
    """SPEC.yaml의 endpoints를 정규화 집합과 원문 표기로 돌려준다."""
    out = {}
    for item in (raw.get("endpoints") or []):
        if isinstance(item, dict):
            item = item.get("endpoint", "")
        s = str(item).strip()
        parts = s.split(None, 1)
        if len(parts) != 2 or parts[0].upper() not in HTTP_VERBS:
            continue
        out[_norm_ep(parts[0], parts[1])] = s
    return out


def _java_annotations(raw):
    """(어노테이션 원문, 붙은 대상) 목록. 대상은 'type' 또는 'member'.

    클래스에 붙은 `@RequestMapping`은 기준 경로이고 메서드에 붙은 것은 엔드포인트다.
    둘을 구분하지 않으면 메서드 수준 `@RequestMapping`을 기준 경로로 오인해
    **정상 코드에 없는 누락을 만들어낸다.** 어노테이션 다음에 오는 선언을 보고 정한다.
    """
    out, pending, buf, depth = [], [], "", 0
    for ln in raw.splitlines():
        st = ln.strip()
        if buf or st.startswith("@"):
            buf += (" " if buf else "") + st
            depth += st.count("(") - st.count(")")
            if depth <= 0:
                pending.append(buf)
                buf, depth = "", 0
            continue
        if not st or st.startswith(("//", "*", "/*")):
            continue
        if pending:
            owner = "type" if JAVA_TYPE_DECL.search(st) else "member"
            out.extend((a, owner) for a in pending)
            pending = []
    return out


def _java_endpoint(ann):
    """어노테이션 하나에서 (verb, 부분경로) 목록을 뽑는다."""
    m = JAVA_VERB_MAP.match(ann)
    if m:
        return [(m.group(1).upper(), m.group(2) or "")]
    m = JAVA_REQ_MAP.match(ann)
    if not m:
        return []
    body = m.group(1) or ""
    pm = JAVA_ANN_PATH.search(body)
    path = pm.group(1) if pm else ""
    verbs = JAVA_ANN_VERB.findall(body) or ["GET"]   # method 미지정은 GET으로 본다
    return [(v, path) for v in verbs]


def _code_roots(raw):
    """SPEC.yaml의 code_roots를 경로 목록으로 정규화한다.

    같은 정리를 check_spec·changeset_report가 각자 하고 있었다. 축 T2가 세 번째
    사본을 만들 자리였으므로 여기로 모은다 — 사본이 늘면 한쪽만 고쳐지고 갈라진다.
    """
    return [str(r).strip().strip("/") for r in (raw.get("code_roots") or []) if str(r).strip()]


def _under_code_roots(rel, code_roots):
    """rel(ROOT 기준 상대경로)이 code_roots 중 하나의 아래에 있는가.

    code_roots가 비어 있으면 저장소 전체가 대상이다 — 이 키를 쓰지 않는 프로젝트는
    동작이 그대로다. 지정하면 그 경로 밖은 명세 대조에서 아예 보지 않는다.

    저장소에 «공개 표면이 아닌 코드»가 함께 있을 때 필요하다. 예제 프로젝트,
    채점·테스트용 픽스처, 모노레포의 다른 서비스가 그렇다. 그 컨트롤러들은 S4(명세
    대비 과잉 구현)에 잡히지만 명세에 올릴 대상이 아니다. exclude로 우회하면 항목이
    콘텐츠 증가에 비례해 늘고, 「우리 표면이지만 관리하지 않는다」와 「애초에 우리
    코드가 아니다」가 한 목록에 섞여 읽는 사람이 둘을 구분할 수 없게 된다.
    """
    if not code_roots:
        return True
    rel_norm = rel.replace(os.sep, "/")
    return any(rel_norm == r or rel_norm.startswith(r.rstrip("/") + "/") for r in code_roots)


def _code_endpoints(code_roots=None):
    """코드에서 실제로 노출된 엔드포인트를 뽑는다. code_roots는 위 _under_code_roots 참고."""
    found = {}
    for p in walk((".java",)):
        rel = os.path.relpath(p, ROOT)
        if not _under_code_roots(rel, code_roots):
            continue
        base = ""
        for ann, owner in _java_annotations(open(p, encoding="utf-8", errors="ignore").read()):
            if owner == "type":
                m = JAVA_REQ_MAP.match(ann)                 # 클래스의 @RequestMapping은 기준 경로
                pm = JAVA_ANN_PATH.search(m.group(1)) if (m and m.group(1)) else None
                if pm:
                    base = pm.group(1)
                continue
            for verb, sub in _java_endpoint(ann):
                full = (base.rstrip("/") + "/" + sub.strip("/")) if sub else base
                found[_norm_ep(verb, full)] = (f"{verb} {full or '/'}", rel)
    for p in walk((".py",)):
        if not _under_code_roots(os.path.relpath(p, ROOT), code_roots):
            continue
        raw = open(p, encoding="utf-8", errors="ignore").read()
        for mm in PY_ROUTE.finditer(raw):
            verb, sub = mm.group(1).upper(), mm.group(2)
            found[_norm_ep(verb, sub)] = (f"{verb} {sub}", os.path.relpath(p, ROOT))
        for mm in PY_FLASK.finditer(raw):
            sub, rest = mm.group(1), mm.group(2)
            verbs = re.findall(r'["\'](' + "|".join(HTTP_VERBS) + r')["\']', rest.upper()) or ["GET"]
            for v in verbs:
                found[_norm_ep(v, sub)] = (f"{v} {sub}", os.path.relpath(p, ROOT))
    return found


def check_spec():
    """명세와 코드의 공개 표면을 집합 비교한다.

    명세에 있는데 코드에 없으면 누락, 코드에 있는데 명세에 없으면 과잉 구현이다.
    둘 다 BLOCK이다. 의도한 예외는 SPEC.yaml의 exclude에 사유와 함께 적는다.
    """
    path = os.path.join(ROOT, SPEC_FILE)
    if not os.path.exists(path):
        return                                  # 명세를 쓰지 않는 프로젝트는 건너뛴다
    try:
        raw = _load_spec(path)
    except Exception as e:
        add("BLOCK", "S0", f"{SPEC_FILE} parse failed: {e}")
        return

    invalid = []
    for i, item in enumerate(raw.get("endpoints") or [], 1):
        value = item.get("endpoint", "") if isinstance(item, dict) else str(item)
        parts = value.strip().split(None, 1)
        if len(parts) != 2 or parts[0].upper() not in HTTP_VERBS or not parts[1].startswith("/"):
            invalid.append(f"endpoints[{i}]: {value or '<empty>'}")
    for i, item in enumerate(raw.get("exclude") or [], 1):
        if not isinstance(item, dict):
            invalid.append(f"exclude[{i}]: structured endpoint and reason required")
            continue
        value, reason = str(item.get("endpoint", "")).strip(), str(item.get("reason", "")).strip()
        parts = value.split(None, 1)
        if len(parts) != 2 or parts[0].upper() not in HTTP_VERBS or not parts[1].startswith("/"):
            invalid.append(f"exclude[{i}].endpoint: {value or '<empty>'}")
        if not reason:
            invalid.append(f"exclude[{i}].reason: required")
    # 없는 경로를 code_roots에 적으면 스캔 대상이 통째로 비어 "코드에서 엔드포인트를
    # 찾지 못함"(S3)으로 빠진다 — 그 메시지는 "아직 안 만들었거나 미지원 프레임워크"를
    # 안내하므로 설정 오타가 미구현으로 위장된다. 오타는 오타라고 말해야 한다.
    for i, r in enumerate(raw.get("code_roots") or [], 1):
        rel = str(r).strip().strip("/")
        if not rel:
            invalid.append(f"code_roots[{i}]: <empty>")
        elif not os.path.isdir(os.path.join(ROOT, rel)):
            invalid.append(f"code_roots[{i}]: no such directory: {rel}")
    if invalid:
        add("BLOCK", "S0", f"{SPEC_FILE} has {len(invalid)} invalid item(s)",
            "\n".join("    " + x for x in invalid[:10]))
        return

    spec = _spec_endpoints(raw)
    if not (raw.get("endpoints") or []):
        return                                  # HTTP 공개 표면이 없으면 이 축을 끈다
    if not spec:
        add("BLOCK", "S0", f"{SPEC_FILE} has no valid endpoints",
            "    format: `- GET /api/orders/{id}`")
        return

    excl = {_norm_ep(*s.split(None, 1)) for s in
            (str(x.get("endpoint", "")) if isinstance(x, dict) else str(x)
             for x in (raw.get("exclude") or []))
            if len(s.split(None, 1)) == 2 and s.split()[0].upper() in HTTP_VERBS}

    code_roots = _code_roots(raw)
    code = _code_endpoints(code_roots)
    if not code:
        # 항목마다 누락을 내면 화면이 덮인다. 원인이 둘뿐이므로 한 줄로 낸다.
        add("INFO" if COMMIT_MODE else "BLOCK", "S3",
            f"no endpoints found in code — all {len(spec)} spec items unimplemented",
            "    either not yet built, or an unsupported framework (Spring/FastAPI/Flask only).\n"
            "    if the latter, empty SPEC.yaml to disable this axis or add an extraction rule to gate.py")
        return
    missing = sorted(k for k in spec if k not in code and k not in excl)
    extra = sorted(k for k in code if k not in spec and k not in excl)

    if missing:
        add("INFO" if COMMIT_MODE else "BLOCK", "S3",
            f"{len(missing)} endpoints in spec but not implemented"
            + (" — pending, normal during build" if COMMIT_MODE else " — missing"),
            "\n".join(f"    {spec[k]}" for k in missing[:10]))
    if extra:
        add("BLOCK", "S4",
            f"{len(extra)} endpoints not in spec — excess implementation",
            "\n".join(f"    {code[k][0]}  ← {code[k][1]}" for k in extra[:10])
            + "\n    delete them, or add to SPEC.yaml via /design §5 (spec amendment)."
            + "\n    exclude is for framework-provided paths — do not use it to resolve this")


def check_spec_test_coverage():
    """명세 항목마다 그 경로를 참조하는 테스트가 있는지 본다.

    T1은 테스트 파일이 하나라도 있는지만 본다. 그래서 첫 항목만 테스트를 쓰고 나머지는
    구현만 하고 넘어가는 상태를 통과시킨다 — 구현을 먼저 하고 테스트를 나중에 쓸 때
    실제로 나는 실패 모양이다. 테스트를 먼저 쓰면 이 축이 애초에 뜨지 않는다.

    경로 리터럴을 문자열로 찾는다. 상수·변수로 조립한 경로는 잡히지 않으므로 미탐이
    남는다. 그래서 BLOCK이 아니라 WARN이다 — 오탐이든 미탐이든 사람이 축을 끄게 만드는
    쪽이 더 나쁘다.
    """
    path = os.path.join(ROOT, SPEC_FILE)
    if not os.path.exists(path):
        return
    try:
        raw = _load_spec(path)
    except Exception:
        return
    spec = _spec_endpoints(raw)
    if not spec:
        return
    all_tests = [p for p in walk((".py", ".java", ".kt", ".js", ".ts"))
                 if re.search(r"test|spec", os.path.basename(p), re.I)]
    if not all_tests:
        return                      # 테스트가 아예 없는 것은 T1이 판정한다
    # check_spec이 code_roots 밖의 코드를 보지 않으므로 이쪽도 같은 범위를 쓴다.
    # 예제 프로젝트나 채점 픽스처의 테스트가 우리 명세 경로와 같은 문자열을 담고 있으면,
    # 범위를 맞추지 않으면 그것이 우리 항목을 충족한 것으로 계산된다 — 미탐이다.
    #
    # 조기 반환은 저장소 전체를 기준으로 판단한다. 걸러낸 뒤의 빈 목록으로 판단하면
    # 「저장소에 테스트는 있지만 우리 코드 범위에는 하나도 없다」가 T1·T2 사이로 빠진다.
    # T1은 파일 하나만 있으면 통과하므로 그쪽도 잡지 못한다.
    code_roots = _code_roots(raw)
    tests = [p for p in all_tests
             if _under_code_roots(os.path.relpath(p, ROOT), code_roots)]
    blob = "\n".join(open(p, encoding="utf-8", errors="ignore").read() for p in tests)
    # 경로 변수는 테스트에서 실제 값으로 바뀌므로 변수를 제거하고 남는 리터럴 조각을
    # 전부 요구한다. 변수 앞까지만 자르면 조각이 부모 컬렉션으로 줄어들어,
    # `/api/orders` 테스트 하나가 `/api/orders/{id}`까지 충족한 것으로 계산된다.
    #   GET /api/orders            → ["/api/orders"]
    #   GET /api/orders/{id}       → ["/api/orders/"]          ← 끝의 / 를 남겨 구분한다
    #   GET /api/customers/{id}/orders → ["/api/customers/", "/orders"]
    missing = []
    for norm, disp in sorted(spec.items()):
        p_only = disp.split(" ", 1)[1] if " " in disp else disp
        frags = [f for f in re.split(r"\{[^}]*\}|<[^>]*>", p_only) if len(f) > 1]
        if frags and not all(f in blob for f in frags):
            missing.append(disp)
    if missing:
        add("WARN", "T2",
            f"{len(missing)}/{len(spec)} spec endpoint(s) have no test referencing their path",
            "\n".join("    " + m for m in missing[:8])
            + "\n    수용 기준을 테스트로 옮기지 않은 항목이다. 경로를 상수로 조립했다면 미탐일 수 있다")


# ═══ 8.5. API 설계 규칙 — 명세 자체의 품질 ══════════════════════════════
# 축 S는 명세와 코드가 **일치하는지**만 본다. 명세 자체가 옳은지는 보지 못하고,
# /design이 그 판단을 사람에게 맡긴다. 그런데 사람이 눈으로 읽을 때 놓치기 쉬운
# 항목 중 기계가 확실히 세는 것이 있다. 특히 A4는 설계서에서 한 줄이라 그냥
# 지나가지만, 잘못 호출되면 컬렉션 전체가 되돌릴 수 없게 사라진다.
# 근거는 Microsoft Azure API 설계 지침(RESTful web API design)과
# reference/design-review-checklist.md §3·§5다.
#
# 이 축은 코드를 읽지 않는다. SPEC.yaml의 문자열만 본다. 설계 단계에서 이미
# 판정이 나야 의미가 있고, 구현이 끝난 뒤에 잡으면 고치는 비용이 달라진다.
URI_VERBS = ("create|get|list|update|delete|remove|add|fetch|modify|edit|insert|"
             "save|register|send|find|search|check|make|set|do|query|retrieve|new")
URI_VERB_NOUN = re.compile(r"^(?:" + URI_VERBS + r")[-_]\w", re.I)
URI_VERB_ONLY = re.compile(r"^(?:" + URI_VERBS + r")$", re.I)
VERSION_SEG = re.compile(r"^v\d+$", re.I)
# 영어 복수형 판정은 규칙만으로 끝나지 않는다. 자주 쓰이는 불규칙형만 담고,
# 판정할 수 없는 것은 판정하지 않는다 — 모르는 것을 틀리게 세면 축을 끄게 된다.
IRREGULAR_PLURAL = {"people", "children", "men", "women", "data", "media",
                    "criteria", "indices", "matrices", "analyses", "series", "news"}


def _is_plural(seg):
    """복수형이면 True, 단수형이면 False, 판정 불가면 None."""
    s = seg.lower()
    if s in IRREGULAR_PLURAL:
        return True
    if not re.fullmatch(r"[a-z][a-z0-9-]*", s):
        return None                             # 영어 복수형 규칙이 통하지 않으므로 판정하지 않는다
    if s.endswith("ss"):
        return False                            # address·class를 복수로 오판하지 않도록 뺀다
    return s.endswith("s")


def _spec_raw_endpoints(raw):
    """(verb, 경로, 원문, 사유) 목록.

    _spec_endpoints는 대조용이라 경로를 정규화하지만, 이 축은 이름 자체를 보므로
    원문 경로가 필요하다. 사유는 A4의 예외 선언에 쓴다.
    """
    out = []
    for item in (raw.get("endpoints") or []):
        reason = ""
        if isinstance(item, dict):
            reason = str(item.get("reason", "")).strip()
            item = item.get("endpoint", "")
        s = str(item).strip()
        parts = s.split(None, 1)
        if len(parts) != 2 or parts[0].upper() not in HTTP_VERBS:
            continue
        out.append((parts[0].upper(), parts[1], s, reason))
    return out


def check_api_design():
    """SPEC.yaml의 공개 표면이 API 설계 관례를 따르는지 본다."""
    path = os.path.join(ROOT, SPEC_FILE)
    if not os.path.exists(path):
        return
    try:
        raw = _load_spec(path)
    except Exception:
        return                                  # 형식 오류는 S0이 이미 내므로 중복해 내지 않는다
    eps = _spec_raw_endpoints(raw)
    if not eps:
        return

    verb_noun, verb_only, singular, deep, bulk = [], [], [], [], []
    versioned, plain = [], []

    for verb, raw_path, src, reason in eps:
        segs = [s for s in _norm_path(raw_path).split("/") if s]
        if not segs:
            continue
        (versioned if any(VERSION_SEG.match(s) for s in segs[:2]) else plain).append(src)

        for i, seg in enumerate(segs):
            if seg == "{}":
                continue
            if URI_VERB_NOUN.match(seg):
                verb_noun.append(f"{src}  ← `{seg}`")
            elif URI_VERB_ONLY.match(seg):
                verb_only.append(f"{src}  ← `{seg}`")
            # 뒤에 경로 변수가 오는 세그먼트는 컬렉션이 확실하다. 그 외에는
            # 컬렉션인지 단일 리소스인지 이름만으로 가릴 수 없어 판정하지 않는다.
            if i + 1 < len(segs) and segs[i + 1] == "{}" and _is_plural(seg) is False:
                singular.append(f"{src}  ← `{seg}` → `{seg}s`")

        nvar = segs.count("{}")
        if nvar >= 3 or (nvar >= 2 and segs[-1] != "{}"):
            deep.append(src)

        if verb in ("PUT", "DELETE") and segs[-1] != "{}" \
                and _is_plural(segs[-1]) is True and not reason:
            bulk.append(src)

    if verb_noun:
        add("BLOCK", "A1", f"{len(verb_noun)} endpoint(s) put a verb in the URI",
            "\n".join("    " + x for x in verb_noun[:8])
            + "\n    HTTP 메서드가 이미 동사다. `POST /create-order` → `POST /orders`")
    if verb_only:
        add("WARN", "A1", f"{len(verb_only)} endpoint(s) use a bare verb segment",
            "\n".join("    " + x for x in verb_only[:6])
            + "\n    계산기형 의사 리소스면 그대로 두되, 최소한만 쓴다")
    if singular:
        add("WARN", "A2", f"{len(singular)} collection(s) named in the singular",
            "\n".join("    " + x for x in singular[:6])
            + "\n    항목이 딸린 세그먼트는 컬렉션이므로 복수형으로 쓴다")
    if deep:
        add("WARN", "A3", f"{len(deep)} endpoint(s) nested deeper than collection/item/collection",
            "\n".join("    " + x for x in deep[:6])
            + "\n    관계가 바뀌면 깊은 경로는 전부 깨진다. 분리 조회로 나눌 것")
    if bulk:
        add("BLOCK", "A4", f"{len(bulk)} bulk PUT/DELETE on a collection — one call wipes the set",
            "\n".join("    " + x for x in bulk[:8])
            + "\n    지우거나, 정말 필요하면 사유를 달아 의도를 남긴다:\n"
              "      - endpoint: DELETE /api/orders\n"
              "        reason: 관리자 일괄 정리 — 필터 필수·감사 로그 적용\n"
            + "    exclude는 명세 관리 밖 경로용이다. 이 항목에 쓰면 S3·S4 대조가 함께 꺼진다")
    if versioned and plain:
        add("WARN", "A5",
            f"version prefix used on {len(versioned)} endpoint(s) but not on {len(plain)}",
            "\n".join("    " + x for x in plain[:6])
            + "\n    버전 전략은 하나로 통일한다. 섞이면 캐시 키와 클라이언트 계약이 갈라진다")


# ═══ 9. 내부 자산 유출 · 미해결 라벨 ════════════════════════════════════
# 하네스가 작업용으로 쓰는 표기(라벨·태그)는 제출물에 남으면 안 된다.
# 라벨 잔존은 CLAUDE.md가 "완료 불가"로 규정하지만 여태 검사 주체가 없었다.
HARNESS_OWNED = (
    "CLAUDE.md", "PROJECT_STATE.md", "PROJECT_LOG.md", "SPEC.yaml",
    "README.md", "USER_GUIDE.md", "MAINTENANCE.md", "CHANGELOG.md",
)
HARNESS_DIRS = ("reference", "tools", ".claude", "prompts")
# prompts/는 최종 산출물이 아니라 그것을 만들 실행 주체에게 넘기는 지시문이다
# (File Map "산출물 프롬프트 생성"). [미검증]·[확인 필요] 같은 라벨이 여기 나오면
# "실행 주체가 이 라벨을 만나면 지우지 말고 그대로 옮기라"는 지시일 수 있어
# reference·tools·.claude와 같은 부류로 뺀다. 이 구분 없이 문자열만 보면 지시문
# 자체가 미해결 라벨로 잡혀 L1이 발행을 막는다 — 하네스가 자기 산출물을 자기
# 검사에 걸리게 두는 셈이다.
OPEN_LABEL = re.compile(r"\[미검증\]|\[확인 필요\]")
INTERNAL_TAG = re.compile(r"\[피드백\s*\d*\]|\[검증\s*\d*\]|\[리뷰\s*\d*\]|\[회귀\s*\d*\]")


def _deliverables():
    """제출물 후보. 하네스 자신의 파일은 뺀다(작업용 표기가 정상적으로 들어 있다)."""
    for p in walk((".py", ".java", ".md", ".yaml", ".yml", ".txt", ".json")):
        rel = os.path.relpath(p, ROOT).replace(os.sep, "/")
        if rel in HARNESS_OWNED:
            continue
        if rel.split("/")[0] in HARNESS_DIRS:
            continue
        yield rel, p


def check_internal_leak():
    labels, tags = defaultdict(list), defaultdict(list)
    for rel, p in _deliverables():
        try:
            txt = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        for i, line in enumerate(txt.splitlines(), 1):
            if OPEN_LABEL.search(line):
                labels[rel].append(i)
            if INTERNAL_TAG.search(line):
                tags[rel].append(i)
    if labels:
        add("BLOCK", "L1",
            f"unresolved labels remain in {len(labels)} deliverable files — completion blocked",
            "\n".join(f"    {k}:{v[:3]}" for k, v in list(labels.items())[:6])
            + "\n    근거를 확보해 라벨을 지우거나, 해당 서술을 제출물에서 뺄 것")
    if tags:
        add("BLOCK", "L2",
            f"harness-internal tags remain in {len(tags)} deliverable files",
            "\n".join(f"    {k}:{v[:3]}" for k, v in list(tags.items())[:6])
            + "\n    주석은 태그·번호 없이 원인 → 과정 → 결론으로 다시 쓸 것.\n"
            + "    지적↔코드 대응은 PROJECT_LOG.md 피드백 대장이 커밋 해시로 갖는다")


def changeset_report():
    """커밋되지 않은 변경을 기능(명세 항목) 기준으로 묶어 보여준다.

    묶음의 근거는 추측이 아니라 코드에서 실제로 추출한 엔드포인트다.
    엔드포인트를 선언하지 않는 파일은 공통·기반으로 분류해 사람이 판단하게 남긴다.
    """
    if not os.path.isdir(os.path.join(ROOT, ".git")):
        print("\n╭─ changeset\n│ not a git repository\n╰─\n")
        return 0

    status = sh("git status --porcelain=v1 -uall")
    changed = []
    for ln in status.splitlines():
        if not ln.strip():
            continue
        path = ln[3:].strip()
        if " -> " in path:                      # rename
            path = path.split(" -> ", 1)[1]
        changed.append((ln[:2].strip() or "??", path.strip('"')))
    if not changed:
        print("\n╭─ changeset\n│ no uncommitted changes\n╰─\n")
        return 0

    code_roots = []
    spec_path = os.path.join(ROOT, SPEC_FILE)
    if os.path.exists(spec_path):
        try:
            code_roots = _code_roots(_load_spec(spec_path))
        except Exception:
            code_roots = []                      # 리포트는 최선 노력이다 — 파싱 실패로 죽지 않는다

    by_file = defaultdict(list)
    for norm, (disp, rel) in _code_endpoints(code_roots).items():
        by_file[rel].append(disp)

    groups, shared = defaultdict(list), []
    for st, rel in changed:
        eps = by_file.get(rel)
        if eps:
            for e in sorted(eps):
                groups[e].append((st, rel))
        else:
            shared.append((st, rel))

    print(f"\n╭─ changeset: {os.path.basename(ROOT)}")
    for ep in sorted(groups):
        print(f"│ ● {ep}")
        for st, rel in sorted(groups[ep]):
            print(f"│     {st:2} {rel}")
    if shared:
        print("│ ○ 공통·기반 / 미분류 — 어느 기능에 속하는지 사람이 판단한다")
        for st, rel in sorted(shared):
            print(f"│     {st:2} {rel}")
    print(f"╰─ {len(changed)} files · {len(groups)} feature group(s) · {len(shared)} unclassified\n")
    return 0


def check_tests_run():
    """커밋 직전에 기능 테스트를 실제로 실행한다.

    테스트 파일의 존재(T1)와 테스트가 통과한다는 것은 다른 사실이다.
    실행 명령은 프로젝트마다 다르므로 SPEC.yaml의 test_command에서 읽는다.
    """
    if not COMMIT_MODE:
        return
    path = os.path.join(ROOT, SPEC_FILE)
    cmd = None
    if os.path.exists(path):
        try:
            cmd = _load_spec(path).get("test_command")
        except Exception:
            cmd = None
    if not cmd:
        add("WARN", "V1", "no test_command in SPEC.yaml — tests not verified mechanically",
            "    SPEC.yaml에 `test_command: \"./gradlew test\"` 형태로 적으면 커밋 직전에 실행한다")
        return
    rc, out, err = _run(cmd, timeout=900)
    if rc is None:
        add("BLOCK", "V1", f"test command failed to run: {err}")
        return
    if rc != 0:
        tail = "\n".join((out + err).strip().splitlines()[-12:])
        add("BLOCK", "V1", f"tests failed (exit {rc}): {cmd}",
            "\n".join("    " + ln for ln in tail.splitlines()))
    else:
        add("INFO", "V1", f"tests passed: {cmd}")


# ═══ 9.5 보안 — 자격증명 노출 · 취약 코드 · 취약 의존성 ═════════════════
# 불변 카드의 우선순위 1·2번이 법규 준수와 오류 위험 방지인데, 여태 그 두 항목의
# 가장 흔한 실패를 검사하는 축이 없었다. 키를 코드에 박고 커밋하는 것, 그리고
# 업계가 이미 아는 취약 패턴이다. L1·L2는 하네스 내부 표기 누출을 잡는 축이고
# 자격증명과는 무관하다. publishing-rules.md의 민감정보 점검은 게시 단계의 산문
# 대상이라 코드를 보지 않는다. 즉 코드 경로에는 검사 주체가 아예 없었다.
#
# X1은 정규식이라 즉시 끝나므로 항상 돈다. X2·X3은 외부 도구를 부르고 수십 초가
# 걸리므로 커밋 직전(COMMIT_MODE)에만 돈다 — V1(테스트 실행)과 같은 자리다.
# 관례가 굳은 뒤 같은 검사를 항목마다 반복해도 새 정보가 나오지 않는다.
#
# 문서(.md)는 대상에서 뺀다. 자격증명이 실제로 새는 자리는 코드와 설정이고,
# 문서에는 검사 자체를 설명하는 예시 문자열이 정상적으로 들어간다.
CODE_EXTS = (".py", ".java", ".kt", ".js", ".jsx", ".ts", ".tsx", ".go", ".rb",
             ".php", ".cs", ".sh", ".bash", ".zsh", ".sql", ".yaml", ".yml",
             ".json", ".xml", ".properties", ".toml", ".ini", ".conf", ".cfg",
             ".tf", ".tfvars", ".gradle", ".env")

# 형식 자체가 자격증명임을 증명하는 패턴만 넣는다. 발급 기관이 접두어와 길이를
# 고정해 두었으므로 우연히 일치하지 않는다.
SECRET_PATTERNS = [
    ("AWS access key id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("private key block", re.compile(r"-----BEGIN (?:[A-Z ]+ )?PRIVATE KEY-----")),
    ("GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b")),
    ("Slack token", re.compile(r"\bxox[abprs]-[A-Za-z0-9-]{10,}")),
    ("Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
    ("Anthropic API key", re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}")),
    ("OpenAI API key", re.compile(r"\bsk-(?:proj-)?[A-Za-z0-9]{32,}\b")),
    ("JWT", re.compile(r"\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}")),
    ("DSN with inline password", re.compile(
        r"\b(?:jdbc:[a-z0-9]+:|mongodb(?:\+srv)?://|postgres(?:ql)?://|mysql://|"
        r"redis://|amqp://)[^\s\"'<>]*:[^\s\"'<>@/]{4,}@")),
]
# 이름이 자격증명인 변수에 문자열 리터럴을 직접 넣은 자리. 형식으로는 증명되지
# 않으므로 자리표시자·환경변수 참조를 걸러낸 뒤에만 센다.
ASSIGN_SECRET = re.compile(
    r"(?i)\b(pass(?:word|wd)|secret|token|api[_-]?key|access[_-]?key|"
    r"private[_-]?key|client[_-]?secret|auth[_-]?token)\b\s*[:=]\s*"
    r"[\"']([^\"']{8,})[\"']")
# 자리표시자를 BLOCK으로 잡으면 정상 저장소가 막히고, 그러면 축 전체를 끄게 된다.
# H1이 예전에 __pycache__로 같은 실패를 했다. 참조·예시는 값이 아니다.
# 배포 구성·환경 파일의 목록형 환경변수는 인용부호가 없다: `- DB_PASSWORD=값`.
# 위 패턴은 따옴표를 요구하므로 이 표기를 통과시켰다. 값이 박힌 것은 같다.
ASSIGN_SECRET_BARE = re.compile(
    r"(?i)^\s*-?\s*[\w.]*(pass(?:word|wd)|secret|token|api[_-]?key|access[_-]?key|"
    r"private[_-]?key|client[_-]?secret|auth[_-]?token)\s*=\s*([^\s\"']{8,})\s*$")
PLACEHOLDER = re.compile(
    r"(?i)(^\s*$|your|example|sample|dummy|placeholder|change[_-]?me|redacted|"
    r"masked|todo|fixme|xxx|\*{3,}|\.\.\.|test|fake|^\$\{|^\{\{|^<|"
    r"os\.environ|getenv|process\.env|^%[a-z_]+%$|^\$[A-Z_]+$)")


def _mask(v):
    return (v[:4] + "…" if len(v) > 4 else "…") + f"({len(v)} chars)"


def _security_targets():
    """검사 대상 코드·설정 파일. git 저장소면 추적 중인 것만 본다.

    추적되지 않은 파일은 커밋되지 않으므로 유출 경로가 아니다. 전체 디스크를
    검사하면 .venv의 테스트 픽스처까지 잡혀 H1과 같은 오탐 실패를 되풀이한다.
    """
    tracked = tracked_set()
    for p in walk(CODE_EXTS):
        rel = os.path.relpath(p, ROOT).replace(os.sep, "/")
        if tracked is not None and rel not in tracked:
            continue
        # 검사를 정의하는 파일은 검사 대상이 아니다. 자기 테스트는 탐지기가 도는지
        # 확인하려고 실제 키 형식을 넣어야 하므로, 잡히는 것이 정상 동작이다.
        # gate.py 자신은 walk()가 이미 제외한다.
        if rel == "tools/test_gate.py":
            continue
        yield rel, p


def check_secrets():
    hits = defaultdict(list)
    for rel, p in _security_targets():
        try:
            txt = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        for i, line in enumerate(txt.splitlines(), 1):
            if len(line) > 4000:                 # 압축·번들 파일은 사람이 쓴 코드가 아니다
                continue
            for name, rx in SECRET_PATTERNS:
                m = rx.search(line)
                if m:
                    hits[rel].append((i, name, _mask(m.group(0))))
            m = ASSIGN_SECRET.search(line) or ASSIGN_SECRET_BARE.match(line)
            if m and not PLACEHOLDER.search(m.group(2)):
                hits[rel].append((i, f"{m.group(1)} literal", _mask(m.group(2))))
    if hits:
        n = sum(len(v) for v in hits.values())
        add("BLOCK", "X1",
            f"{n} hardcoded credential(s) in {len(hits)} file(s)",
            "\n".join(f"    {rel}:{i} {name} {val}"
                      for rel, v in list(hits.items())[:8] for i, name, val in v[:3])
            + "\n    값을 환경변수·시크릿 저장소로 옮기고, 이미 커밋됐다면 해당 키를 폐기·재발급할 것.\n"
            + "    코드에서 지우는 것만으로는 git 이력에 남은 값이 사라지지 않는다")


def check_sast():
    """semgrep으로 알려진 취약 패턴을 본다. 커밋 직전에만 돈다.

    `--config auto`가 아니라 `p/security-audit`을 쓰고 `--metrics=off`를 붙인다.
    auto는 프로젝트 정보를 레지스트리로 보낸다 — 불변 카드의 데이터 등급 규칙이
    금지하는 방향이다. 이 조합은 규칙만 내려받고 코드는 로컬에 남는다.
    """
    if not COMMIT_MODE:
        return
    if not any(True for _ in _security_targets()):
        return
    if shutil.which("semgrep") is None:
        add("WARN", "X2", "semgrep not installed — known vulnerability patterns not checked",
            "    `pipx install semgrep` 또는 `brew install semgrep` 후 다시 돌릴 것.\n"
            "    설치 없이는 이 축이 통과가 아니라 미검사 상태다")
        return
    rc, out, err = _run("semgrep scan --config p/security-audit --json --quiet "
                        "--metrics=off --timeout 60", timeout=900)
    if rc is None or not out.strip():
        add("WARN", "X2", "semgrep did not produce a result — not checked",
            "\n".join("    " + ln for ln in (err or "no output").splitlines()[:6]))
        return
    try:
        res = json.loads(out).get("results", [])
    except Exception as e:
        add("WARN", "X2", f"semgrep output parse failed: {e}")
        return
    by_sev = defaultdict(list)
    for f in res:
        sev = (f.get("extra") or {}).get("severity", "INFO").upper()
        by_sev[sev].append(
            f"    {f.get('path')}:{(f.get('start') or {}).get('line', '?')} "
            f"{f.get('check_id', '?').split('.')[-1]}")
    if by_sev["ERROR"]:
        add("BLOCK", "X2", f"semgrep: {len(by_sev['ERROR'])} high-severity finding(s)",
            "\n".join(by_sev["ERROR"][:8]))
    if by_sev["WARNING"]:
        add("WARN", "X2", f"semgrep: {len(by_sev['WARNING'])} medium-severity finding(s)",
            "\n".join(by_sev["WARNING"][:6]))
    if not by_sev["ERROR"] and not by_sev["WARNING"]:
        add("INFO", "X2", "semgrep: no security findings")


def check_deps():
    """의존성의 알려진 취약점. 매니페스트가 있는 생태계만 본다.

    도구가 없으면 WARN이다 — 통과가 아니라 미검사임을 남긴다. Gradle·Maven은
    별도 플러그인 설정이 필요해 저장소마다 다르므로 여기서 대신 실행하지 않고,
    검사되지 않은 사실만 알린다.
    """
    if not COMMIT_MODE:
        return
    has = lambda *f: any(os.path.exists(os.path.join(ROOT, x)) for x in f)

    if has("package-lock.json", "npm-shrinkwrap.json"):
        if shutil.which("npm") is None:
            add("WARN", "X3", "package-lock.json present but npm not available — deps not audited")
        else:
            rc, out, _ = _run("npm audit --json", timeout=600)
            try:
                v = json.loads(out).get("metadata", {}).get("vulnerabilities", {})
            except Exception:
                v = {}
            sev = v.get("critical", 0) + v.get("high", 0)
            if sev:
                add("BLOCK", "X3", f"npm audit: {sev} critical/high vulnerable dependency(ies)",
                    f"    critical={v.get('critical', 0)} high={v.get('high', 0)} "
                    f"moderate={v.get('moderate', 0)}\n"
                    "    `npm audit fix` 또는 해당 패키지 교체. 고칠 수 없으면 사유를 문서에 남길 것")
            elif v:
                add("INFO", "X3", f"npm audit: no critical/high (moderate={v.get('moderate', 0)})")

    if has("requirements.txt", "pyproject.toml", "poetry.lock", "Pipfile.lock"):
        if shutil.which("pip-audit") is None:
            add("WARN", "X3", "python manifest present but pip-audit not installed — deps not audited",
                "    `pipx install pip-audit` 후 다시 돌릴 것")
        else:
            rc, out, _ = _run("pip-audit -f json --progress-spinner off", timeout=600)
            try:
                data = json.loads(out)
                deps = data.get("dependencies", data if isinstance(data, list) else [])
                bad = [d for d in deps if d.get("vulns")]
            except Exception:
                bad = []
            if bad:
                add("BLOCK", "X3", f"pip-audit: {len(bad)} vulnerable dependency(ies)",
                    "\n".join(f"    {d.get('name')} {d.get('version')} — "
                              + ",".join(v.get("id", "?") for v in d["vulns"][:3])
                              for d in bad[:8]))
            elif rc == 0:
                add("INFO", "X3", "pip-audit: no vulnerable dependencies")

    if has("build.gradle", "build.gradle.kts", "pom.xml"):
        add("WARN", "X3", "JVM dependencies are not audited by this gate",
            "    OWASP dependency-check 또는 `gradle dependencyUpdates`를 빌드에 붙이고,\n"
            "    그 결과를 커밋 전 확인 절차에 넣을 것 — 이 게이트는 대신 실행하지 않는다")


# ═══ 9.6 인프라 하드닝 — 격리 · 상태 확인 · 비교 연산 ════════════════════
# 축 X는 코드에 박힌 자격증명을 본다. 이 축은 그 바깥, 배포 구성이 만드는 노출을
# 본다. 앱 코드가 완전해도 데이터 계층이 호스트에 포트를 열어두면 앱을 거치지 않는
# 경로가 남고, 그 경로는 애플리케이션 검증을 전부 우회한다.
# 판정 기준의 원문은 `reference/insights/backend-hardening.md`이고 여기서는 그중
# 기계가 셀 수 있는 것만 센다. 축 A와 같은 갈래다 — 우리 산출물에서 아직 나지 않은
# 결함도 업계가 이미 아는 것이면 미리 막되, 오탐 위험이 낮은 항목만 고른다.
#
# 전 항목 WARN으로 시작한다. D5와 같은 이유다. 오탐률을 모르는 상태로 BLOCK을 켜면
# 정상 구성이 막히고, 그러면 축 전체를 끄게 된다. 검출 로그를 쌓아 오탐이 없다고
# 확인한 뒤에만 이 스위치를 올린다.
I_BLOCK = False
I_LEVEL = "BLOCK" if I_BLOCK else "WARN"

COMPOSE_FILE = re.compile(r"(?:^|/)(?:docker-)?compose(?:[.\w-]*)?\.ya?ml$")
# 데이터·메시지 계층. 외부와 직접 통신할 이유가 없는 계층만 넣는다.
DATA_TIER = re.compile(
    r"(?i)(postgres|mysql|mariadb|mongo|redis|memcached|elastic|opensearch|"
    r"rabbitmq|kafka|clickhouse|cassandra)")


def _top_blocks(txt):
    """최상위 키 → 그 아래 블록 본문.

    범용 YAML 파서가 아니다. `_load_spec`과 같은 이유로 외부 패키지를 요구하지 않기
    위한 최소 구현이며, 이 축이 보는 키(services·networks)만 다룬다.
    """
    blocks, key, buf = {}, None, []
    for raw in txt.splitlines():
        line = _strip_yaml_comment(raw).rstrip()
        if not line.strip():
            continue
        if not line[:1].isspace():
            if key:
                blocks[key] = "\n".join(buf)
            key, buf = (line.split(":", 1)[0].strip() if ":" in line else None), []
        elif key:
            buf.append(line)
    if key:
        blocks[key] = "\n".join(buf)
    return blocks


def _children(block):
    """블록의 첫 들여쓰기 단계 키 → 그 하위 본문."""
    lines = [l for l in block.splitlines() if l.strip()]
    if not lines:
        return {}
    base = min(len(l) - len(l.lstrip()) for l in lines)
    out, key, buf = {}, None, []
    for l in lines:
        if len(l) - len(l.lstrip()) == base and ":" in l:
            if key:
                out[key] = "\n".join(buf)
            key, buf = l.strip().split(":", 1)[0].strip().lstrip("- "), []
        elif key:
            buf.append(l)
    if key:
        out[key] = "\n".join(buf)
    return out


# `- name` 과 `name:` 두 표기를 같게 읽는다. 값이 붙은 줄(condition: ...)은 걸리지 않는다.
REF_NAME = re.compile(r"^\s*-?\s*([\w.-]+):?\s*$", re.M)


def _is_data_tier(name, body):
    image = re.search(r"^\s*image:\s*(\S+)", body, re.M)
    return bool(DATA_TIER.search(name) or (image and DATA_TIER.search(image.group(1))))


def check_infra_compose():
    """배포 구성이 만드는 노출을 본다. 구성 파일이 없으면 이 축은 돌지 않는다."""
    exposed, unguarded, unisolated, unready = [], [], [], []
    for p in walk((".yml", ".yaml")):
        rel = os.path.relpath(p, ROOT).replace(os.sep, "/")
        if not COMPOSE_FILE.search(rel):
            continue
        try:
            txt = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        top = _top_blocks(txt)
        if "services" not in top:
            continue
        svcs = _children(top["services"])
        internal = {n for n, b in _children(top.get("networks", "")).items()
                    if re.search(r"^\s*internal:\s*true\s*$", b, re.M)}
        for name, body in svcs.items():
            fields = _children(body)
            data = _is_data_tier(name, body)
            if data and "ports" in fields:
                exposed.append(f"{rel} {name}")
            if data and internal:
                joined = set(REF_NAME.findall(fields.get("networks", "")))
                if not joined & internal:
                    unisolated.append(f"{rel} {name}")
            if not re.search(r"^\s*user:", body, re.M) or \
               not re.search(r"^\s*read_only:\s*true\s*$", body, re.M):
                unguarded.append(f"{rel} {name}")
            for dep in REF_NAME.findall(fields.get("depends_on", "")):
                if dep in svcs and "healthcheck" not in _children(svcs[dep]):
                    unready.append(f"{rel} {name} → {dep}")
    if exposed:
        add(I_LEVEL, "I1", f"{len(exposed)} data-tier service(s) publish a host port",
            "\n".join("    " + s for s in exposed[:8])
            + "\n    앱을 거치지 않는 경로가 생긴다. 외부 진입점은 프록시 하나로 모으고,\n"
              "    개발 편의로 열었다면 그 구성을 배포 구성과 분리할 것")
    if unguarded:
        add(I_LEVEL, "I2", f"{len(unguarded)} service(s) miss non-root or read-only rootfs",
            "\n".join("    " + s for s in unguarded[:8])
            + "\n    `user:`와 `read_only: true`는 한 세트다. 한쪽만 걸면 미완료다 —\n"
              "    read-only를 켜면 드러나는 쓰기 경로만 개별 허용할 것")
    if unisolated:
        add(I_LEVEL, "I5", f"{len(unisolated)} data-tier service(s) not on an internal-only network",
            "\n".join("    " + s for s in unisolated[:8])
            + "\n    앱 계층이 뚫려도 데이터가 밖으로 나갈 경로 자체를 없애는 것이 목적이다")
    if unready:
        add(I_LEVEL, "I3", f"{len(unready)} dependency(ies) declared without a healthcheck on the target",
            "\n".join("    " + s for s in unready[:8])
            + "\n    기동 순서만 보장되고 받을 준비는 보장되지 않는다. 대상 서비스에\n"
              "    의존 자원까지 확인하는 healthcheck를 걸 것")


HEALTH_ROUTE = re.compile(
    r'@[\w.]+\.(?:route|get)\s*\(\s*[fr]?["\']([^"\']*)["\']')
HEALTH_PATH = re.compile(r"(?i)(health|healthz|readi|ready|live)")
# 의존 자원을 실제로 건드렸다는 흔적. 하나라도 있으면 정적 응답이 아니다.
DEP_CALL = re.compile(
    r"(?i)\b(cursor|execute|conn|connection|session|engine|ping|redis|client|"
    r"repository|select|query|fetch|scalar|db)\b")


def check_health_endpoint():
    """상태 확인이 의존 자원까지 보는지 본다. 파이썬 라우트만 대상으로 한다.

    다른 언어까지 넓히면 본문 경계를 정확히 잡지 못해 오탐이 난다. 검사하지 못하는
    스택은 `reference/insights/backend-hardening.md` §5가 사람 판단으로 맡는다.
    """
    flat = []
    for rel, p in _security_targets():
        if not rel.endswith(".py"):
            continue
        try:
            lines = open(p, encoding="utf-8", errors="ignore").read().splitlines()
        except Exception:
            continue
        for i, line in enumerate(lines):
            m = HEALTH_ROUTE.search(line)
            if not m or not HEALTH_PATH.search(m.group(1)):
                continue
            body, started = [], False
            for nxt in lines[i + 1:i + 30]:
                if not nxt.strip():
                    continue
                if started and not nxt[:1].isspace():
                    break
                if nxt.lstrip().startswith(("def ", "async def ")):
                    started = True
                    continue
                if started:
                    body.append(nxt)
            if body and not DEP_CALL.search("\n".join(body)):
                flat.append(f"{rel}:{i + 1} {m.group(1)}")
    if flat:
        add(I_LEVEL, "I3", f"{len(flat)} health endpoint(s) return a static response",
            "\n".join("    " + s for s in flat[:8])
            + "\n    의존 자원이 죽어도 healthy로 보인다. 「프로세스가 살아 있다」가 아니라\n"
              "    「의존하는 자원까지 동작한다」를 확인할 것")


# 이름이 비밀값인 변수를 일반 비교 연산자로 비교한 자리. 길이와 조기 종료로 시간차가 샌다.
SECRET_CMP = re.compile(
    r"(?i)\b(\w*(?:token|secret|passwd|password|api_?key|admin_?key|"
    r"signature|hmac|digest)\w*)\s*(?:==|!=)\s*(\S+)")
# 존재 확인은 비밀값 비교가 아니다. 이미 상수 시간 비교를 쓰는 줄도 제외한다.
CMP_EXEMPT = re.compile(
    r"(?i)^(none|null|nil|undefined|true|false|\"\"|''|0\b|-1\b|len\()")
CMP_SAFE = re.compile(
    r"(?i)(compare_digest|timingsafeequal|messagedigest\.isequal|"
    r"constant_?time|secure_?compare)")


def check_secret_compare():
    hits = []
    for rel, p in _security_targets():
        try:
            txt = open(p, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        for i, line in enumerate(txt.splitlines(), 1):
            if len(line) > 4000 or CMP_SAFE.search(line):
                continue
            m = SECRET_CMP.search(line)
            if m and not CMP_EXEMPT.match(m.group(2)):
                hits.append(f"{rel}:{i} {m.group(1)}")
    if hits:
        add(I_LEVEL, "I4", f"{len(hits)} secret comparison(s) not constant-time",
            "\n".join("    " + s for s in hits[:8])
            + "\n    일반 비교는 길이·조기 종료로 시간차를 흘린다. 상수 시간 비교로 바꿀 것\n"
              "    (python `hmac.compare_digest`, java `MessageDigest.isEqual`,\n"
              "     node `crypto.timingSafeEqual`)")


# ═══ 10. 보고서 브리프 — 작성 전에 판단·근거를 고정하는가 ═══════════════
REPORT_PROFILES = {"technical-project", "business-strategy", "policy-research", "brief"}


def check_report_brief():
    """얇은 보고서 브리프만 검사한다. 최종 문체·한계는 D축이 맡는다."""
    briefs = [p for p in walk((".json",)) if os.path.basename(p) == "report-brief.json"]
    for path in briefs:
        rel = os.path.relpath(path, ROOT)
        try:
            brief = json.load(open(path, encoding="utf-8"))
        except Exception as e:
            add("BLOCK", "R0", f"{rel}: parse failed: {e}")
            continue

        if not isinstance(brief, dict):
            add("BLOCK", "R0", f"{rel}: root must be a JSON object")
            continue

        missing = []
        for key in ("profile", "profile_reason", "audience", "decision"):
            if not isinstance(brief.get(key), str) or not brief[key].strip():
                missing.append(key)
        claims, outline = brief.get("claims"), brief.get("outline")
        if not isinstance(claims, list) or not claims:
            missing.append("claims(list)")
        if (not isinstance(outline, list) or not outline
                or any(not isinstance(x, str) or not x.strip() for x in outline)):
            missing.append("outline(non-empty string list)")
        counter = brief.get("counterevidence")
        if (not isinstance(counter, list)
                or any(not isinstance(x, str) or not x.strip() for x in counter)):
            missing.append("counterevidence(string list; empty allowed)")
        profile = brief.get("profile")
        if isinstance(profile, str) and profile and profile not in REPORT_PROFILES:
            missing.append(f"profile({profile})")
        if missing:
            add("BLOCK", "R1", f"{rel}: report judgment is incomplete — {', '.join(missing)}",
                "    독자·독자가 내릴 결정·핵심 주장·구성은 작성 전에 한 번만 고정한다")

        bad_claims = []
        if not isinstance(claims, list):
            bad_claims.append("claims: list required")
            claims = []
        for i, claim in enumerate(claims, 1):
            if not isinstance(claim, dict):
                bad_claims.append(f"claim {i}: object required")
                continue
            lacks = []
            if not isinstance(claim.get("statement"), str) or not claim["statement"].strip():
                lacks.append("statement")
            evidence = claim.get("evidence")
            if (not isinstance(evidence, list) or not evidence
                    or any(not isinstance(x, str) or not x.strip() for x in evidence)):
                lacks.append("evidence(non-empty string list)")
            if claim.get("status") not in (None, "", "verified", "partially-verified"):
                lacks.append("status must be verified or partially-verified")
            elif claim.get("status") in (None, ""):
                lacks.append("status")
            elif claim.get("status") == "partially-verified":
                for key in ("verified_scope", "limitation"):
                    if not isinstance(claim.get(key), str) or not claim[key].strip():
                        lacks.append(key)
            if lacks:
                bad_claims.append(f"claim {i}: {', '.join(lacks)}")
        if bad_claims:
            add("BLOCK", "R2", f"{rel}: {len(bad_claims)} claim(s) lack usable evidence",
                "\n".join("    " + x for x in bad_claims[:8]))

        bad_visuals, visuals = [], brief.get("visuals", [])
        if not isinstance(visuals, list):
            bad_visuals.append("visuals: list required")
            visuals = []
        for i, visual in enumerate(visuals, 1):
            if (not isinstance(visual, dict)
                    or not isinstance(visual.get("message"), str) or not visual["message"].strip()
                    or not isinstance(visual.get("evidence"), list) or not visual["evidence"]
                    or any(not isinstance(x, str) or not x.strip() for x in visual["evidence"])):
                bad_visuals.append(f"visual {i}: message and evidence are both required")
        if bad_visuals:
            add("BLOCK", "R3", f"{rel}: {len(bad_visuals)} decorative/unsupported visual(s)",
                "\n".join("    " + x for x in bad_visuals[:8]))

        if len(open(path, encoding="utf-8").read()) > 12000:
            add("WARN", "R4", f"{rel}: brief exceeds 12,000 characters — likely copying source prose",
                "    원문을 복사하지 말고 주장과 근거 위치만 남긴다")


# ═══ 11. 슬라이드 계약 — 판단 밀도·비대칭·도메인 집중 ══════════════════
# AI 티는 문체가 아니라 (1) 판단의 부재 (2) 과도한 대칭 (3) 도메인 무국적성에서 나온다.
# 맞춤법이 아니라 구조 통계를 본다. 대상은 `deck.json` 또는 `*.deck.json`.
MIN_THRESHOLD_RATIO = 0.15   # 수치 기준을 가진 항목 비율 하한
MIN_LEN_STDEV = 8.0          # 항목 길이 표준편차 하한
MIN_COUNT_STDEV = 0.6        # 슬라이드별 항목 수 표준편차 하한
MAX_DOMAIN_DRIFT = 0.4       # 주 도메인 밖 예시 허용 비율
MAX_LINES_PER_SLIDE = 9

DECK_FILLER = [
    "매우 중요", "필수적", "다양한", "효과적으로", "적절하게",
    "핵심적인 역할", "중요한 역할", "빼놓을 수 없", "간과할 수 없",
    "살펴보도록", "알아보도록", "종합적으로", "전반적으로",
]
DECK_NARRATIVE = re.compile(r"(합니다|습니다|입니다|해요|이다)\s*$")
DECK_JUDGED = ("How", "Recommendation")
DECK_PROBED = ("concept", "technique")
DOMAIN_LEXICON = {
    "manufacturing": ["불량", "공정", "설비", "수율", "센서", "라인", "양산", "호기", "레시피", "재검사", "압력", "진동"],
    "finance":       ["여신", "연체", "sharpe", "drawdown", "거래", "신용", "포트폴리오"],
    "healthcare":    ["환자", "진단", "bmi", "임상", "병변", "처방"],
    "ecommerce":     ["구매", "장바구니", "전환", "rfm", "리텐션", "클릭"],
    "telco":         ["이탈", "churn", "요금제", "가입자", "트래픽"],
    "public":        ["민원", "인허가", "세수", "행정"],
    # IT는 강의 주제 자체인 경우가 많다. 예시 도메인과 구분하려면 home_domain에
    # ["it", "ecommerce"]처럼 배열로 선언한다.
    "it":            ["엔드포인트", "컨트롤러", "리포지토리", "dto", "트랜잭션", "롤백",
                      "마이그레이션", "스키마", "인덱스", "쿼리", "브랜치", "배포",
                      "컨테이너", "도커", "쿠버네티스", "파이프라인", "빌드", "런타임",
                      "spring", "jpa", "orm", "미들웨어", "캐시", "세션", "토큰",
                      "인증", "인가", "리팩터링", "커버리지", "스택트레이스",
                      "타임아웃", "재시도", "헬스체크", "로드밸런서", "api"],
}


def _deck_files():
    for p in walk((".json",)):
        n = os.path.basename(p)
        if n == "deck.json" or n.endswith(".deck.json"):
            yield p


def _deck_items(deck):
    for sl in deck.get("slides", []):
        for b in sl.get("blocks", []):
            for it in b.get("items", []):
                if isinstance(it, dict) and it.get("text"):
                    yield sl, b, it


def check_deck():
    """슬라이드 스펙에서 AI 지문을 구조 통계로 검출한다."""
    for path in _deck_files():
        rel = os.path.relpath(path, ROOT)
        try:
            deck = json.load(open(path, encoding="utf-8"))
        except Exception as e:
            add("BLOCK", "K0", f"{rel}: parse failed: {e}")
            continue
        items = list(_deck_items(deck))
        if not items:
            add("BLOCK", "K0", f"{rel}: no slide items found",
                "    구조: slides[].blocks[].items[].text")
            continue

        # K1 판단 밀도 — 수치 기준이 없으면 교과서 요약이다
        have = [it for _, _, it in items if it.get("threshold") not in (None, "", [])]
        ratio = len(have) / len(items)
        if ratio < MIN_THRESHOLD_RATIO:
            add("BLOCK", "K1", f"{rel}: judgment density {len(have)}/{len(items)} ({ratio:.0%}) "
                f"— floor {MIN_THRESHOLD_RATIO:.0%}",
                "    '검토한다' 대신 '결측 10% 이하면 row 제거'처럼 수치를 박을 것")

        # K2 실패 조건 — 방법을 제시하면 언제 깨지는지 함께 쓴다
        miss = [(sl, b, it) for sl, b, it in items
                if b.get("label") in DECK_JUDGED and not it.get("failure_mode")]
        if miss:
            add("BLOCK", "K2", f"{rel}: {len(miss)} method items without failure_mode",
                "\n".join(f'    {sl.get("id","?")} / {b.get("label")}: "{it["text"][:32]}…"'
                          for sl, b, it in miss[:6])
                + "\n    그 방법이 오히려 해가 되는 조건을 쓸 것. '주의 필요'는 조건이 아니다")

        # K3 사고 유도 질문
        noprobe = [sl for sl in deck.get("slides", [])
                   if sl.get("kind") in DECK_PROBED and not sl.get("probe")]
        if noprobe:
            add("WARN", "K3", f"{rel}: {len(noprobe)} concept/technique slides without probe",
                "    슬라이드가 답하지 않는 질문 1개를 넣을 것")

        # K4 과도한 대칭 — 사람은 장마다 같은 개수로 쓰지 않는다
        counts = [sum(len(b.get("items", [])) for b in sl.get("blocks", []))
                  for sl in deck.get("slides", []) if sl.get("kind") not in ("section", "closing")]
        counts = [c for c in counts if c]
        if len(counts) >= 4:
            sd = st.pstdev(counts)
            if sd < MIN_COUNT_STDEV:
                add("WARN", "K4", f"{rel}: bullet-count stdev {sd:.2f} — too symmetric",
                    f"    분포 {Counter(counts).most_common()}. 정보량이 많은 장은 늘리고 적은 장은 줄일 것")

        # K5 길이 균일성
        lens = [len(it["text"]) for _, _, it in items]
        if len(lens) >= 10:
            sd = st.pstdev(lens)
            if sd < MIN_LEN_STDEV:
                add("WARN", "K5", f"{rel}: item-length stdev {sd:.1f} (mean {st.mean(lens):.0f})",
                    "    짧은 단정과 조건절 붙은 긴 줄을 의도적으로 섞을 것")

        # K6 내용 없는 수식어 · 서술형 종결
        fillers, narr = [], []
        for sl, b, it in items:
            low = it["text"].lower()
            for ph in DECK_FILLER:
                if ph in low:
                    fillers.append((sl.get("id", "?"), ph))
            if DECK_NARRATIVE.search(it["text"]):
                narr.append(sl.get("id", "?"))
        if fillers:
            add("BLOCK", "K6", f"{rel}: {len(fillers)} filler phrases",
                "\n".join(f'    {i}: "{ph}"' for i, ph in fillers[:6])
                + "\n    정보가 없는 수식어. 삭제하거나 수치로 대체")
        if narr:
            add("WARN", "K7", f"{rel}: {len(narr)} narrative endings — deck style is nominal",
                f"    {', '.join(sorted(set(narr))[:6])} — 명사형(~음/~함)으로 통일")

        # K8 도메인 집중 — 사람은 자기 밥벌이 도메인에 쏠린다
        meta = deck.get("meta") or {}
        home = meta.get("home_domain")
        homes = [home] if isinstance(home, str) else list(home or [])
        homes = [h for h in homes if h and h != "generic"]
        # 강의 주제 자체의 어휘는 드리프트 계산에서 뺀다. IT 강의처럼 주제어가
        # 전 슬라이드에 깔리는 경우 그것이 카운트를 포화시켜 검사가 무력해진다.
        subj = meta.get("subject_domain")
        subjects = [subj] if isinstance(subj, str) else list(subj or [])
        subjects = [x for x in subjects if x and x not in homes]
        if homes:
            corpus = []
            for sl in deck.get("slides", []):
                corpus += [sl.get("probe") or "", sl.get("subtitle") or ""]
            for _, _, it in items:
                corpus += [it["text"], it.get("failure_mode") or ""]
                corpus += list(it.get("sub") or [])
            hits = Counter()
            for line in corpus:
                t = line.lower()
                for dom, words in DOMAIN_LEXICON.items():
                    if any(w in t for w in words):
                        hits[dom] += 1
            total = sum(hits.values())
            for x in subjects:
                hits.pop(x, None)
            total = sum(hits.values())
            own = sum(hits[h] for h in homes)
            label = "+".join(homes)
            if subjects:
                label += f" (subject {'+'.join(subjects)} 제외)"
            if total < 4:
                add("WARN", "K8", f"{rel}: almost no domain vocabulary — examples are abstract",
                    f"    {label} 현장 어휘를 최소 4곳에 박을 것")
            elif 1 - (own / total) > MAX_DOMAIN_DRIFT:
                add("WARN", "K8", f"{rel}: home domain({label}) {own}/{total} — drifting",
                    f"    분포 {dict(hits)}. 도메인을 골고루 흩뿌리면 생성물 티가 난다")

        # K9 부제가 제목의 반복 · 과밀
        for sl in deck.get("slides", []):
            t, sub = (sl.get("title") or "").lower(), (sl.get("subtitle") or "").lower()
            if sub and (t in sub or sub in t):
                add("WARN", "K9", f'{rel} {sl.get("id","?")}: subtitle echoes title',
                    "    부제는 주장을 담을 것. 제목의 부연이 아니다")
            n = sum(len(b.get("items", [])) + sum(len(i.get("sub") or [])
                    for i in b.get("items", []) if isinstance(i, dict))
                    for b in sl.get("blocks", []))
            if n > MAX_LINES_PER_SLIDE:
                add("BLOCK", "K9", f'{rel} {sl.get("id","?")}: {n} lines (max {MAX_LINES_PER_SLIDE})',
                    "    개념을 쪼개 슬라이드를 분리할 것")


# ═══ 12. 산출물 계약 — PDF는 게이트 사각지대였다 ════════════════════════
# check_docs()는 .md만 본다. 실제 제출물인 PDF의 커버리지가 0이었다.
# 여기서 PDF 자체를 검사하고(D7·D8), Markdown·HTML·PDF가 한 문서인지 확인한다(E1~E4).
TOKENS_CSS = os.path.join(os.path.dirname(SELF), "..", "reference", "report.css")


def _css_block(css, scope):
    """한 규칙 블록만 잘라 온다. 닫는 중괄호까지 안 자르면 값이 없는 블록에서
    파일 뒤쪽 다른 축의 값을 주워 온다."""
    i = css.find(scope)
    if i < 0:
        return ""
    end = css.find("}", i)
    return css[i:end if end > 0 else len(css)]


def _css_mm(css, name, scope):
    m = re.search(re.escape("--" + name) + r":\s*([\d.]+)mm", _css_block(css, scope))
    return float(m.group(1)) if m else None


# 조판 축 → report.css의 해당 블록. 축이 늘면 여기만 고친다.
AXIS_SCOPE = {"l-classic": ".l-classic {", "l-modern": ".l-modern {",
              "l-formal": ".l-formal {"}


def _css_tokens():
    """조판 값의 단일 원본을 읽는다. 게이트가 자기 기준을 따로 갖지 않게 한다."""
    try:
        css = open(TOKENS_CSS, encoding="utf-8").read()
    except Exception:
        return {}
    t = {"axis": {}}
    m = re.search(r"@page\s*\{[^}]*size:\s*([A-Za-z0-9]+)", css)
    if m:
        t["size"] = m.group(1).upper()
    m = re.search(r"--body-w:\s*([\d.]+)mm", _css_block(css, ".report {"))
    if m:
        t["body_w"] = float(m.group(1))
    for axis, scope in AXIS_SCOPE.items():
        t["axis"][axis] = {
            "body_w": _css_mm(css, "body-w", scope) or t.get("body_w"),
            "mt": _css_mm(css, "mt", scope), "mb": _css_mm(css, "mb", scope),
            "ml": _css_mm(css, "ml", scope), "mr": _css_mm(css, "mr", scope),
        }
    return t


def _body_axis(htxt):
    """보고서 HTML의 <body class>에서 조판 축 하나를 뽑는다."""
    m = re.search(r"<body[^>]*class=[\"']([^\"']*)[\"']", htxt)
    cls = set(m.group(1).split()) if m else set()
    return next((a for a in AXIS_SCOPE if a in cls), None)


PAGE_PT = {"A4": (595.0, 842.0)}


def _pdf_text(p, layout=False):
    q = "'" + p.replace("'", "'\\''") + "'"
    return sh(f"pdftotext {'-layout ' if layout else ''}{q} -") or ""


def _md_of(pdf):
    base = os.path.splitext(pdf)[0]
    for cand in (base + ".md", base + ".MD"):
        if os.path.isfile(cand):
            return cand
    stem = unicodedata.normalize("NFC", os.path.basename(base))
    for p in walk((".md",)):
        if unicodedata.normalize("NFC", os.path.basename(os.path.splitext(p)[0])) == stem:
            return p
    return None


# E5를 BLOCK으로 승격하는 스위치. D5와 같은 이유로 처음엔 WARN만 낸다 — brief처럼
# 짧은 프로필이 정당하게 .row/.aside 없이 끝나는 경우가 있는지 검출률로 먼저 확인한다.
E5_BLOCK = False

PT_PER_MM = 72 / 25.4
# 글리프 바운딩 박스는 활자 크기보다 조금 크게 잡힌다. 그 여유만 허용한다.
BOX_TOL_MM = 0.6
# 쪽번호는 판면 밖(하단 여백 안)에 정상적으로 놓이므로 집계에서 뺀다.
PNUM_MAX_W_MM = 20.0


def _check_page_box(pdf, rel, ax):
    """렌더된 PDF의 콘텐츠가 판면(--mt/--mb/--ml/--mr) 안에 있는지 쪽마다 잰다."""
    if not all(ax.get(k) for k in ("mt", "mb", "ml", "mr")):
        return
    try:
        import pymupdf
    except ImportError:
        add("INFO", "E7", f"{rel}: pymupdf가 없어 판면 좌표 검사를 건너뛴다",
            "    pip install pymupdf — 하단 여백 침범은 육안 검토로는 잡히지 않는다")
        return

    top, bottom = ax["mt"], 297.0 - ax["mb"]
    left, right = ax["ml"], 210.0 - ax["mr"]
    doc = pymupdf.open(pdf)
    total = doc.page_count
    bad, worst = [], None
    for i, page in enumerate(doc, start=1):
        x0 = y0 = float("inf")
        x1 = y1 = float("-inf")
        for b in page.get_text("dict")["blocks"]:
            bx0, by0, bx1, by1 = (v / PT_PER_MM for v in b["bbox"])
            if bx1 - bx0 < 1 or by1 - by0 < 1:
                continue
            if by0 > bottom - 4 and (bx1 - bx0) < PNUM_MAX_W_MM:
                continue  # 쪽번호
            x0, y0 = min(x0, bx0), min(y0, by0)
            x1, y1 = max(x1, bx1), max(y1, by1)
        if x0 == float("inf"):
            continue  # 빈 쪽
        why = []
        # 하단은 표지·목차를 포함해 전 쪽에서 본다. 이 선이 검사의 목적이다.
        if y1 > bottom + BOX_TOL_MM:
            why.append(f"하단 {y1 - bottom:+.1f}mm")
        # 앞장(표지·간지)은 판면을 따르지 않는 게 정상이라 상·좌·우를 면제한다.
        if i > 1:
            if y0 < top - BOX_TOL_MM:
                why.append(f"상단 {top - y0:+.1f}mm")
            if x0 < left - BOX_TOL_MM:
                why.append(f"좌측 {left - x0:+.1f}mm")
            if x1 > right + BOX_TOL_MM:
                why.append(f"우측 {x1 - right:+.1f}mm")
        if why:
            bad.append(f"{i}쪽: {', '.join(why)}")
        room = bottom - y1
        worst = room if worst is None else min(worst, room)
    doc.close()
    if bad:
        add("BLOCK", "E7", f"{rel}: 판면 위반 {len(bad)}쪽 / 전체 {total}쪽",
            "\n".join("    " + b for b in bad[:6])
            + "\n    쪽을 나누거나 표 옆 서술을 줄일 것 — 표 자체를 줄이는 게 아니다")
    elif worst is not None:
        add("INFO", "E7", f"{rel}: 판면 준수 — 하단 여유 최소 {worst:.1f}mm")


def check_report_artifacts():
    # check_hygiene이 이미 git 추적 파일만 보는 것과 같은 이유다. 이 검사에만 그
    # 기준이 적용되지 않아, .gitignore로 막아둔 로컬 PDF(기획 원본·외부에서 받은
    # 자료 등 커밋 대상이 아닌 것)까지 "편집 가능한 원본이 없다"로 잡혔다.
    # 저장소가 의도적으로 추적에서 뺀 파일을 검사 대상으로 삼는 것은 오탐이다.
    tracked = tracked_set()
    pdfs = [p for p in walk((".pdf",))
            if tracked is None or os.path.relpath(p, ROOT).replace(os.sep, "/") in tracked]
    if not pdfs:
        return
    tok = _css_tokens()
    for pdf in pdfs:
        rel = os.path.relpath(pdf, ROOT)
        md = _md_of(pdf)
        html = os.path.splitext(pdf)[0] + ".html"
        stem = unicodedata.normalize("NFC", os.path.basename(os.path.splitext(pdf)[0]))
        if not os.path.isfile(html):
            html = next((p for p in walk((".html",))
                         if unicodedata.normalize("NFC",
                            os.path.basename(os.path.splitext(p)[0])) == stem), None)

        axis = None
        if html and os.path.isfile(html):
            htxt = open(html, encoding="utf-8", errors="ignore").read()
            axis = _body_axis(htxt)

            # E5 비대칭 2단 축인데 report.css의 .row/.aside 구조를 한 번도 안 씀.
            # 표지(.cover-head/.cover-meta)는 애초에 이 클래스를 쓰지 않으므로 따로 뺄
            # 필요가 없다 — 문서 전체에 없다는 것 자체가 본문에서 안 썼다는 뜻이다.
            # l-formal도 같은 구조를 쓴다. 주석열 위치만 반대(좌측)라 검사는 동일하다.
            if axis in ("l-modern", "l-formal"):
                has_row = re.search(r'class=["\'][^"\']*\brow\b', htxt)
                has_aside = re.search(r'class=["\'][^"\']*\baside\b', htxt)
                if not (has_row or has_aside):
                    add("BLOCK" if E5_BLOCK else "WARN", "E5",
                        f"{rel}: {axis} 조판인데 .row/.aside를 쓰지 않음 — "
                        "report.css의 비대칭 2단 구조가 무시됨",
                        "    본문을 --body-w로 좁히고 캡션·측정조건을 --aside-w 열로 보낼 것"
                        " (report-style.md §수치·증거 표기)")

            # E6 인라인 style 금지. 조판 값의 단일 원본은 report.css다 — HTML에
            # style="..."이 하나라도 있으면 그 값은 CSS 밖에서 정해진 것이고, 축을
            # 바꾸거나 색을 바꿔도 따라오지 않는다. "이번 한 줄만"을 허용하면 다음
            # 사람이 또 예외를 만들기 때문에 예외를 두지 않는다.
            inline = re.findall(r'style=["\'][^"\']+["\']', htxt)
            if inline:
                hrel = os.path.relpath(html, ROOT)
                add("BLOCK", "E6",
                    f"{hrel}: 인라인 style {len(inline)}건 — 조판 값이 report.css 밖에 있다",
                    "\n".join("    " + s[:70] for s in inline[:4])
                    + "\n    report.css에 클래스를 만들고 거기서만 값을 정할 것")

        # E1 편집 가능한 원본이 없다. PDF만 남으면 문구 하나 고치는 데 전체 재생성이 필요하다
        if not md:
            add("BLOCK", "E1", f"{rel}: PDF exists but no matching .md — no editable source",
                "    Markdown이 단일 사실 원본이다. PDF는 파생물로만 존재할 것")
            continue
        # E2 조판 미리보기가 없다. 요청 여부와 무관하게 항상 있어야 한다
        if not html:
            add("BLOCK", "E2", f"{rel}: PDF exists but no matching .html preview",
                "    HTML은 조판을 확인하는 가장 싼 수단이다. 중간 산출물이라고 숨기지 말 것")

        # E7 판면 준수를 렌더된 PDF에서 쪽 단위로 실측한다.
        #
        # CSS는 하단 여백을 지켜 주지 못한다. 쪽 높이를 고정하고 넘침을 감추면 조판이
        # 깨진 사실만 사라진다. 육안 검토도 못 잡는다 — 실제로 쪽이 넘쳐 다음 쪽으로
        # 밀려난 이미지가 그 쪽의 불투명한 배경 밑에 깔려, 렌더 PNG를 전부 넘겨봐도
        # 보이지 않은 적이 있다(캡션만 앞 쪽에 남아 캡션·이미지가 갈라진 상태였다).
        # 좌표로만 잡힌다. 그래서 이 검사가 BLOCK이다.
        #
        # 아래 D7 축(텍스트 추출)보다 먼저 둔다. 좌표는 텍스트 레이어와 무관하므로
        # 추출이 안 되는 PDF에서도 판면은 여전히 잴 수 있다.
        ax = tok.get("axis", {}).get(axis or "l-modern", {})
        _check_page_box(pdf, rel, ax)

        mtxt = open(md, encoding="utf-8", errors="ignore").read()
        ptxt = _pdf_text(pdf)
        if not ptxt.strip():
            add("WARN", "D7", f"{rel}: no extractable text — scanned or image-only PDF")
            continue

        # E3 Markdown과 PDF를 따로 쓰는 실패 모드를 직접 잡는다.
        #    쪽 번호·러닝 헤더·캡션 번호는 조판 산물이므로 비교에서 뺀다.
        flat = re.sub(r"\s+", "", ptxt)
        heads = [re.sub(r"\s+", "", h) for h in
                 re.findall(r"^#{1,3}\s+(.+?)\s*$", mtxt, re.M)]
        heads = [h for h in heads if len(h) >= 3]
        miss = [h for h in heads if h not in flat]
        if heads and len(miss) / len(heads) > 0.2:
            add("BLOCK", "E3",
                f"{rel}: {len(miss)}/{len(heads)} headings missing from PDF — md and pdf diverged",
                "\n".join("    " + h for h in miss[:5])
                + "\n    Markdown과 PDF를 서로 독립된 문서로 쓰지 말 것")
        nums = set(re.findall(r"\d+\.\d+", mtxt))
        nmiss = [n for n in sorted(nums) if n.replace(".", "") not in flat.replace(".", "")]
        if nums and len(nmiss) / len(nums) > 0.3:
            add("BLOCK", "E3",
                f"{rel}: {len(nmiss)}/{len(nums)} decimal figures missing from PDF",
                "    " + " · ".join(nmiss[:6]))

        # E4 원본이 더 새롭다. 승인 후 고친 Markdown이 PDF에 반영되지 않았다
        if os.path.getmtime(md) > os.path.getmtime(pdf) + 1:
            add("WARN", "E4", f"{rel}: .md is newer than the PDF — re-render needed",
                "    mode: render-only 로 그 Markdown만 읽어 다시 만들 것")

        # D7 PDF 본문에도 문체 축을 적용한다
        check_overuse(rel + " (pdf)", ptxt, axis="D7")
        cv = _sentence_cv(ptxt)
        if cv is not None and cv < 0.45:
            add("WARN", "D7", f"{rel} (pdf): sentence-length CV {cv:.2f} (target 0.45+)")
        ac = _acronyms(ptxt)
        if ac:
            add("WARN", "D7", f"{rel} (pdf): {len(ac)} acronyms spelled out",
                "\n".join("    " + a for a in ac[:4]))

        # D8 조판이 report.css를 따르는지 대조한다
        info = sh(f"pdfinfo '{pdf}'")
        m = re.search(r"Page size:\s*([\d.]+) x ([\d.]+)", info)
        want = PAGE_PT.get(tok.get("size", "A4"))
        if m and want:
            w, h = float(m.group(1)), float(m.group(2))
            if abs(w - want[0]) > 3 or abs(h - want[1]) > 3:
                add("WARN", "D8",
                    f"{rel}: page {w:.0f}x{h:.0f}pt, expected {tok.get('size','A4')} "
                    f"{want[0]:.0f}x{want[1]:.0f}pt")
        fonts = sh(f"pdffonts '{pdf}'")
        rows = [l for l in fonts.splitlines()[2:] if l.strip()]
        if rows and any(re.split(r"\s+", l.strip())[-5:][0].lower() == "no" for l in rows):
            add("WARN", "D8", f"{rel}: some fonts are not embedded — 한글이 깨질 수 있다")
        # 줄 길이 상한은 축마다 다르다. l-formal은 주석열 없는 절(.row.full)이
        # 판면 전폭을 정상적으로 쓰고 표·코드 블록도 전폭이라, classic·modern의
        # 55자를 그대로 걸면 정상 조판에서 오탐이 난다. 축의 --body-w에서 상한을
        # 계산한다 — 한글 본문은 글자 하나가 대략 활자 크기만큼 폭을 먹으므로
        # 폭(mm) / 2.4mm 에 표·전폭 행의 여유 15%를 얹는다.
        lines = [l.rstrip() for l in _pdf_text(pdf, layout=True).splitlines() if l.strip()]
        bw = ax.get("body_w") or tok.get("body_w") or 114.0
        cap = 55 if axis in (None, "l-classic", "l-modern") else round(bw / 2.4 * 1.15)
        if lines:
            avg = sum(len(l.strip()) for l in lines) / len(lines)
            if avg > cap:
                add("WARN", "D8",
                    f"{rel}: avg line {avg:.0f} chars (max {cap}) — column too wide, "
                    f"report.css --body-w is {bw}mm")


# ═══ 12.5. 줄바꿈 단위 ═══════════════════════════════════════════════════
# 자동 줄바꿈은 report.css의 keep-all이 어절 단위로 강제하고 E9가 그 값을 지킨다.
# 손으로 넣은 줄바꿈은 CSS가 닿지 않는다 — 슬라이드 제목처럼 줄 길이를 맞추려고
# 끊는 자리가 그렇다. 그쪽을 여기서 본다.
#
# **이 검사는 어절 경계를 판정하지 못한다.** 「통/째로」가 갈라졌는지는 형태소를
# 분석해야 알 수 있고, 그 판정을 규칙 몇 줄로 흉내내면 정상 문장을 잡는다
# (「할 수」/「있다」의 '수'는 한 글자짜리 정상 어절이다). 그래서 **어절을 시작할 수
# 없는 형태소로 줄이 시작하는 경우**만 센다. 이건 예외가 없다.
# 나머지는 규칙 문서(ppt-style.md·deck-contract.md·report-style.md)와 사람이 본다.
BOUND_MORPHEME = re.compile(
    r"^(습니다|습니까|합니다|입니다|됩니다|했다|한다|된다|됐다|이다|였다|"
    r"에서|에게|한테|께서|으로|부터|까지|로서|로써|지만|면서|이라고|라고|"
    r"하며|이며|처럼|조차|마저)")
# 오탐률을 모르는 상태로 BLOCK을 켜면 정상 산출물이 막힌다. D5·E5와 같은 방식이다.
WRAP_BLOCK = False


def _wrap_breaks(text):
    """줄바꿈 중 어절을 쪼갠 것이 확실한 자리만 돌려준다."""
    bad = []
    parts = re.split(r"<br\s*/?>|\n", str(text))
    for i, seg in enumerate(parts[1:], 1):
        head = seg.lstrip()
        if not head:
            continue
        if BOUND_MORPHEME.match(head):
            tail = parts[i - 1].rstrip()[-12:]
            bad.append(f"…{tail} ⏎ {head[:12]}…")
    return bad


def _deck_texts(deck):
    for sl in deck.get("slides", []):
        for k in ("title", "subtitle", "probe"):
            if sl.get(k):
                yield sl.get("id", "?"), sl[k]
        for b in sl.get("blocks", []):
            for it in b.get("items", []):
                if not isinstance(it, dict):
                    continue
                for k in ("text", "failure_mode"):
                    if it.get(k):
                        yield sl.get("id", "?"), it[k]


def check_wrap_unit():
    """어절 중간에서 끊긴 수동 줄바꿈을 찾는다."""
    for path in _deck_files():
        rel = os.path.relpath(path, ROOT)
        try:
            deck = json.load(open(path, encoding="utf-8"))
        except Exception:
            continue                            # 파싱 실패는 K0이 이미 내므로 건너뛴다
        hits = [f"{sid}: {h}" for sid, txt in _deck_texts(deck) for h in _wrap_breaks(txt)]
        if hits:
            add("BLOCK" if WRAP_BLOCK else "WARN", "K10",
                f"{rel}: {len(hits)} line break(s) split a word",
                "\n".join("    " + x for x in hits[:6])
                + "\n    줄 길이는 문구를 줄여서 맞춘다 — deck-contract.md 규칙 10")

    for rel, path in _deliverables():
        if not rel.endswith((".md", ".html")):
            continue
        try:
            txt = open(path, encoding="utf-8", errors="ignore").read()
        except Exception:
            continue
        # 마크다운의 문단 개행은 렌더링에서 줄바꿈이 아니다. 명시적 <br>만 본다.
        hits = _wrap_breaks(re.sub(r"\n", " ", txt))
        if hits:
            add("BLOCK" if WRAP_BLOCK else "WARN", "E10",
                f"{rel}: {len(hits)} <br> split(s) a word",
                "\n".join("    " + x for x in hits[:6])
                + "\n    제목·표지에서 줄을 맞추려 끊지 않는다 — report-style.md §줄바꿈")


# ═══ 13. 조판 원본 자체의 하드 규칙 ═════════════════════════════════════
# CSS 주석에 "이 값을 쓴다"라고만 적어 두는 방식은, 사람이든 다음 세션의 Claude든
# 편집하다 어겨도 아무도 잡아내지 못한다. 실제로 두 번 났던 문제다.
#   1. 위계별 들여쓰기(장 0·절 4·본문 8mm) 실험을 되돌리며 일부를 놓쳤다.
#   2. l-formal g2에서 .row.full의 margin-left는 0으로 지웠지만
#      .row:not(.full) > .body의 padding-left를 지우는 걸 빠뜨려, 주석열이 있는
#      절의 본문만 3.4mm 밀린 채 육안 검토를 통과했다.
# 둘 다 "참고" 대신 "금지"로 바꿔야 잡힌다. 렌더 좌표가 아니라 소스 규칙을 직접
# 읽으므로 모호함이 없다 — 렌더 좌표로 본문 들여쓰기를 재려던 시도는 세 번 다
# 실패했다. Chrome이 만든 PDF의 텍스트 레이어는 원본 DOM 구조(문단인지 표 셀인지
# 목록 항목인지)를 보존하지 않아, 좌표만으로 그 구조를 되짚을 수 없기 때문이다.
#   3. 어절 단위 줄바꿈(word-break)도 같은 성격이다. 지워도 조판은 그대로 나오고,
#      한글만 글자 중간에서 접힌다 — 영문 문서로 검토하면 끝까지 안 보인다.
INDENT_HINT = ("위계별 단 들여쓰기는 되돌린 실험이다 — "
               "examples/report-style-formal.md §금지")
INDENT_MISS = ".row와 .row.full의 본문이 서로 다른 x에서 시작한다"
WRAP_HINT = ("어절 단위 줄바꿈은 report-style.md·ppt-style.md의 규칙이다. "
             "값을 바꾸려면 그 규칙부터 바꿀 것")
WRAP_MISS = "한글이 「제출한」/「다」처럼 글자 중간에서 접힌다"
CSS_RULES = [
    (".l-formal .sheet.g2 .row.full > .body", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g2 .row:not(.full) > .body", "padding-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g2 h1", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g2 h2", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g3 .row.full > .body", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g3 .row:not(.full) > .body", "padding-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g3 h1", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".l-formal .sheet.g3 h2", "margin-left", "0", INDENT_MISS, INDENT_HINT),
    (".report, .report *", "word-break", "keep-all", WRAP_MISS, WRAP_HINT),
    (".report, .report *", "line-break", "strict", WRAP_MISS, WRAP_HINT),
]


def check_report_css():
    """report.css의 등록된 선택자·속성이 허용값 그대로인지 본다."""
    try:
        css = open(TOKENS_CSS, encoding="utf-8").read()
    except Exception:
        return
    for selector, prop, allowed, miss, hint in CSS_RULES:
        m = re.search(re.escape(selector) + r"\s*\{[^}]*?"
                      + re.escape(prop) + r":\s*([^;}]+)", css)
        if not m:
            add("BLOCK", "E9",
                f"report.css: `{selector} {{ {prop} }}` 규칙이 없다 — "
                "삭제됐거나 선택자가 바뀌었다",
                "    빠지면 " + miss)
        elif m.group(1).strip() != allowed:
            add("BLOCK", "E9",
                f"report.css: `{selector}` {prop}={m.group(1).strip()!r} "
                f"(허용값 {allowed!r}만 가능)",
                "    " + hint)


if CHANGESET_MODE:
    sys.exit(changeset_report())

# 축 X는 검사가 죽은 것을 통과로 읽으면 안 된다. 불변 카드 우선순위 1·2번이고,
# X2·X3의 도구 부재를 이미 "통과가 아니라 미검사"로 내고 있다. 예외로 죽었을 때만
# WARN 한 줄로 지나가면 그 원칙과 어긋난다 — 보안 축만 BLOCK으로 올린다.
SECURITY_CHECKS = (check_secrets, check_sast, check_deps)

for fn in (check_hygiene, check_provenance, check_history,
           check_comments, check_history_comments, check_docs,
           check_surface, check_spec, check_spec_test_coverage, check_api_design,
           check_internal_leak, check_tests_run,
           check_secrets, check_sast, check_deps,
           check_infra_compose, check_health_endpoint, check_secret_compare,
           check_report_brief, check_deck, check_report_artifacts,
           check_wrap_unit, check_report_css):
    try:
        fn()
    except Exception as e:
        lvl = "BLOCK" if fn in SECURITY_CHECKS else "WARN"
        add(lvl, "!!", f"{fn.__name__} failed: {e}",
            "    보안 축이 돌지 않았다. 통과가 아니다" if lvl == "BLOCK" else "")

ORDER = {"BLOCK": 0, "WARN": 1, "INFO": 2}
MARK = {"BLOCK": "■", "WARN": "□", "INFO": "▶"}
findings.sort(key=lambda f: (ORDER.get(f[0], 9), f[1]))
nb = sum(1 for f in findings if f[0] == "BLOCK")
nw = sum(1 for f in findings if f[0] == "WARN")

title = "gate: " + os.path.basename(ROOT) + ("  [commit readiness]" if COMMIT_MODE else "")
print(f"\n╭─ {title}")
for lvl, code, msg, detail in findings:
    print(f"│ {MARK.get(lvl, '·')} [{code}] {msg}")
    if detail:
        print(detail)
if COMMIT_MODE:
    if nb:
        print(f"╰─ NOT READY — {nb} blocker(s), {nw} warning(s). 해소 후 커밋할 것\n")
    else:
        print(f"├─ COMMIT READY — 0 blockers, {nw} warning(s)")
        # 통과하면 곧바로 커밋 분할 원자료를 낸다. 명령을 두 번 치게 하지 않는다.
        changeset_report()
elif not findings:
    print("╰─ pass — 0 findings\n")
else:
    print(f"╰─ BLOCK {nb} · WARN {nw}\n")
sys.exit(1 if nb else 0)
